import type { FastifyInstance } from 'fastify';
import { nanoid } from 'nanoid';
import { z } from 'zod';
import { createReadStream, promises as fs } from 'node:fs';
import path from 'node:path';
import { requireAuth } from './auth.js';
import { indexMessage, setting, setSetting } from './db.js';
import { OCR_DIAGNOSTIC_EXPECTED, ocrDiagnosticImage } from './ocr-diagnostic-image.js';
import { sha256 } from './security.js';

function numericSetting(app:FastifyInstance,key:string,fallback:number){const value=Number(setting(app.db,key));return Number.isFinite(value)&&value>=0?value:fallback;}
function retentionSetting(app:FastifyInstance,key:string){const value=Number(setting(app.db,key));return Number.isInteger(value)&&(value===-1||value>=1)?value:-1;}
const retentionDaysSchema=z.number().int().min(-1).max(3650).refine(value=>value!==0,{message:'retention_days_must_be_minus_one_or_positive'});
type DiagnosticLevel='ok'|'warning'|'error';
type DiagnosticItem={key:string;label:string;level:DiagnosticLevel;detail:string;durationMs:number};
const diagnosticError=(error:unknown)=>error instanceof Error?error.message:'检查失败';
async function runDiagnostics(app:FastifyInstance){const started=Date.now(),items:DiagnosticItem[]=[];let checkStarted=Date.now();try{const rows=app.db.pragma('quick_check') as Record<string,string>[],values=rows.flatMap(row=>Object.values(row));items.push({key:'database',label:'数据库',level:values.length&&values.every(value=>value==='ok')?'ok':'error',detail:values.length?values.join('；'):'未返回检查结果',durationMs:Date.now()-checkStarted});}catch(error){items.push({key:'database',label:'数据库',level:'error',detail:diagnosticError(error),durationMs:Date.now()-checkStarted});}
  const writable=async(key:string,label:string,dir:string)=>{checkStarted=Date.now();const probe=path.join(dir,`.dukou-diagnostic-${nanoid()}.tmp`);try{await fs.writeFile(probe,'ok',{flag:'wx'});const value=await fs.readFile(probe,'utf8');items.push({key,label,level:value==='ok'?'ok':'error',detail:value==='ok'?'可正常读写':'写入内容校验失败',durationMs:Date.now()-checkStarted});}catch(error){items.push({key,label,level:'error',detail:diagnosticError(error),durationMs:Date.now()-checkStarted});}finally{await fs.rm(probe,{force:true}).catch(()=>undefined);}};
  await writable('files','文件存储',app.config.filesDir);await writable('temp','临时目录',app.config.tempDir);
  checkStarted=Date.now();let disk={freeBytes:0,totalBytes:0};try{const stats=await fs.statfs(app.config.dataDir);disk={freeBytes:stats.bavail*stats.bsize,totalBytes:stats.blocks*stats.bsize};const ratio=disk.totalBytes?disk.freeBytes/disk.totalBytes:1;items.push({key:'disk',label:'磁盘空间',level:ratio<.05?'error':ratio<.15?'warning':'ok',detail:`可用 ${Math.round(disk.freeBytes/1048576)} MB / 共 ${Math.round(disk.totalBytes/1048576)} MB`,durationMs:Date.now()-checkStarted});}catch(error){items.push({key:'disk',label:'磁盘空间',level:'warning',detail:diagnosticError(error),durationMs:Date.now()-checkStarted});}
  checkStarted=Date.now();try{const rows=app.db.prepare('SELECT status,count(*) AS count,MIN(updated_at) AS oldest FROM ocr_jobs GROUP BY status').all() as {status:string;count:number;oldest:number|null}[],counts=Object.fromEntries(rows.map(row=>[row.status,row.count])),stale=(app.db.prepare("SELECT count(*) AS count FROM ocr_jobs WHERE status='processing' AND updated_at<?").get(Date.now()-20*60_000) as {count:number}).count,enabled=setting(app.db,'ocr_enabled')!=='false',failed=counts.failed??0,pending=counts.pending??0,processing=counts.processing??0;items.push({key:'ocr',label:'OCR 队列',level:!enabled?'ok':stale?'error':failed?'warning':'ok',detail:!enabled?'已按设置关闭':stale?`${stale} 个任务处理超过 20 分钟`:failed?`${failed} 个失败；${pending} 个排队；${processing} 个处理中`:`${pending} 个排队；${processing} 个处理中；队列正常`,durationMs:Date.now()-checkStarted});}catch(error){items.push({key:'ocr',label:'OCR 队列',level:'error',detail:diagnosticError(error),durationMs:Date.now()-checkStarted});}
  const memory=process.memoryUsage(),level:DiagnosticLevel=items.some(item=>item.level==='error')?'error':items.some(item=>item.level==='warning')?'warning':'ok';return {level,checkedAt:Date.now(),durationMs:Date.now()-started,items,system:{node:process.version,platform:process.platform,arch:process.arch,uptimeSeconds:Math.round(process.uptime()),rssBytes:memory.rss,heapUsedBytes:memory.heapUsed,diskFreeBytes:disk.freeBytes,diskTotalBytes:disk.totalBytes}};}
type OcrDiagnosticResult={level:DiagnosticLevel;status:'done'|'failed'|'timeout'|'disabled';detail:string;recognizedText:string;expectedText:string;matched?:boolean;attempts?:number;durationMs:number};
const wait=(ms:number)=>new Promise(resolve=>setTimeout(resolve,ms));
async function runOcrDiagnostic(app:FastifyInstance):Promise<OcrDiagnosticResult>{
  const started=Date.now(),expectedText=OCR_DIAGNOSTIC_EXPECTED;
  if(setting(app.db,'ocr_enabled')==='false')return {level:'warning',status:'disabled',detail:'OCR 已按设置关闭，未执行真实识别',recognizedText:'',expectedText,durationMs:0};
  const blobId=nanoid(),messageId=nanoid(),jobId=nanoid(),image=Buffer.concat([ocrDiagnosticImage(),Buffer.from(`\n${messageId}`)]),digest=sha256(image),filePath=path.join(app.config.filesDir,digest.slice(0,2),digest);
  try{
    await fs.mkdir(path.dirname(filePath),{recursive:true});await fs.writeFile(filePath,image,{flag:'wx'});
    const now=Date.now();app.db.transaction(()=>{app.db.prepare('INSERT INTO blobs(id,sha256,size,path,mime,ref_count,created_at) VALUES(?,?,?,?,?,?,?)').run(blobId,digest,image.length,filePath,'image/png',1,now);app.db.prepare(`INSERT INTO messages(id,type,file_name,mime,blob_id,size,sha256,source_name,visibility,created_at,updated_at,ocr_status,note) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(messageId,'file','OCR-状态测试.png','image/png',blobId,image.length,digest,'系统状态测试','trusted_only',now,now,'pending','状态测试完成后自动清理');app.db.prepare(`INSERT INTO ocr_jobs(id,message_id,status,attempts,error,created_at,updated_at) VALUES(?,?,'pending',0,NULL,0,?)`).run(jobId,messageId,now);})();
    while(Date.now()-started<30_000){
      const row=app.db.prepare('SELECT j.status,j.attempts,j.error,m.ocr_text AS recognizedText FROM ocr_jobs j JOIN messages m ON m.id=j.message_id WHERE j.id=?').get(jobId) as {status:string;attempts:number;error:string|null;recognizedText:string}|undefined;
      if(row?.status==='done'){
        const recognizedText=(row.recognizedText??'').trim(),normalize=(value:string)=>value.toUpperCase().replace(/[^A-Z0-9]/g,''),matched=normalize(recognizedText).includes(normalize(expectedText)),durationMs=Date.now()-started;
        return {level:matched?'ok':recognizedText?'warning':'error',status:'done',detail:matched?'真实 OCR 识别成功':recognizedText?'OCR 已返回，但内容与测试文本不一致':'OCR 已完成，但未识别到文字',recognizedText,expectedText,matched,attempts:row.attempts,durationMs};
      }
      if(row?.status==='failed')return {level:'error',status:'failed',detail:row.error||'OCR 任务失败',recognizedText:'',expectedText,attempts:row.attempts,durationMs:Date.now()-started};
      await wait(250);
    }
    return {level:'error',status:'timeout',detail:'30 秒内未收到 OCR 返回，独立 OCR 服务可能未运行或被阻塞',recognizedText:'',expectedText,durationMs:Date.now()-started};
  }catch(error){return {level:'error',status:'failed',detail:diagnosticError(error),recognizedText:'',expectedText,durationMs:Date.now()-started};}
  finally{
    try{app.db.transaction(()=>{app.db.prepare('DELETE FROM messages_fts WHERE message_id=?').run(messageId);app.db.prepare('DELETE FROM messages WHERE id=?').run(messageId);app.db.prepare('DELETE FROM blobs WHERE id=?').run(blobId);})();}catch(error){app.log.warn({error,messageId},'failed to clean OCR diagnostic database records');}
    await fs.rm(filePath,{force:true}).catch(error=>app.log.warn({error,messageId},'failed to clean OCR diagnostic image'));
  }
}
function readSettings(app:FastifyInstance){
  const ocrRows=app.db.prepare('SELECT j.status,count(*) AS count FROM ocr_jobs j JOIN messages m ON m.id=j.message_id WHERE m.deleted_at IS NULL GROUP BY j.status').all() as {status:string;count:number}[],ocr={completed:0,pending:0,processing:0,failed:0};for(const row of ocrRows){const key=row.status==='done'?'completed':row.status as keyof typeof ocr;if(key in ocr)ocr[key]=row.count;}
  const storage=app.db.prepare(`SELECT COALESCE((SELECT SUM(size) FROM blobs),0) AS used,COALESCE(SUM(CASE WHEN m.type='text' THEN length(CAST(COALESCE(m.content,'') AS BLOB)) ELSE 0 END),0) AS text,COALESCE(SUM(CASE WHEN m.deleted_at IS NULL AND m.mime LIKE 'image/%' THEN m.size ELSE 0 END),0) AS images,COALESCE(SUM(CASE WHEN m.deleted_at IS NULL AND m.type='file' AND (m.mime IS NULL OR m.mime NOT LIKE 'image/%') THEN m.size ELSE 0 END),0) AS files,COALESCE(SUM(CASE WHEN m.deleted_at IS NOT NULL THEN COALESCE(m.size,length(CAST(COALESCE(m.content,'') AS BLOB))) ELSE 0 END),0) AS trash FROM messages m`).get() as {used:number;text:number;images:number;files:number;trash:number};
  const configuredLimit=numericSetting(app,'storage_limit_bytes',app.config.storageLimitBytes??0);return {ocrEnabled:setting(app.db,'ocr_enabled')!=='false',ocr,storage:{...storage,...(configuredLimit>0?{limit:configuredLimit}:{})},retention:{imagesDays:retentionSetting(app,'images_days'),filesDays:retentionSetting(app,'files_days'),trashDays:retentionSetting(app,'trash_days'),downloadedEarlier:setting(app.db,'downloaded_earlier')==='true'},defaultShare:{expiresIn:numericSetting(app,'default_share_expires',3600),maxDownloads:setting(app.db,'default_share_downloads')===undefined?1:Number(setting(app.db,'default_share_downloads'))||null},branding:{siteTitle:setting(app.db,'site_title')??'渡口',tabTitle:setting(app.db,'tab_title')??'渡口 · 私人传输助手'},pwaIcon:{custom:setting(app.db,'pwa_icon_custom')==='true',version:Number(setting(app.db,'pwa_icon_version'))||2},retentionDays:retentionSetting(app,'files_days')};
}
function requeueOcr(app:FastifyInstance,input:{scope?:'all'|'failed';messageId?:string}){const rows=input.messageId?app.db.prepare("SELECT id FROM messages WHERE id=? AND mime LIKE 'image/%' AND deleted_at IS NULL").all(input.messageId) as {id:string}[]:input.scope==='all'?app.db.prepare("SELECT id FROM messages WHERE mime LIKE 'image/%' AND deleted_at IS NULL").all() as {id:string}[]:app.db.prepare("SELECT j.message_id AS id FROM ocr_jobs j JOIN messages m ON m.id=j.message_id WHERE j.status='failed' AND m.deleted_at IS NULL").all() as {id:string}[];const ts=Date.now();app.db.transaction(()=>{for(const row of rows){app.db.prepare(`INSERT INTO ocr_jobs(id,message_id,status,attempts,error,created_at,updated_at) VALUES(?,?,'pending',0,NULL,?,?) ON CONFLICT(message_id) DO UPDATE SET status='pending',attempts=0,error=NULL,updated_at=excluded.updated_at`).run(nanoid(),row.id,ts,ts);app.db.prepare("UPDATE messages SET ocr_status='pending',updated_at=? WHERE id=?").run(ts,row.id);}})();return rows.length;}

export async function adminRoutes(app:FastifyInstance){
  let ocrDiagnosticRun:Promise<OcrDiagnosticResult>|undefined;
  app.get('/api/devices',{preHandler:requireAuth(app,true)},async()=>({items:app.db.prepare('SELECT id,name,created_at AS createdAt,last_seen_at AS lastSeenAt,last_ip AS lastIp,expires_at AS expiresAt FROM devices WHERE revoked_at IS NULL AND expires_at>? ORDER BY last_seen_at DESC').all(Date.now())}));
  app.patch('/api/devices/:id',{preHandler:requireAuth(app,true)},async(req)=>{const {id}=z.object({id:z.string()}).parse(req.params),{name}=z.object({name:z.string().trim().min(1).max(80)}).parse(req.body);app.db.transaction(()=>{app.db.prepare('UPDATE devices SET name=? WHERE id=? AND revoked_at IS NULL').run(name,id);app.db.prepare('UPDATE sessions SET name=? WHERE device_id=?').run(name,id);app.db.prepare('UPDATE messages SET source_name=? WHERE source_device_id=?').run(name,id);})();app.broadcast({type:'source.renamed'});return {id,name};});
  app.delete('/api/devices/:id',{preHandler:requireAuth(app,true)},async(req)=>{const {id}=z.object({id:z.string()}).parse(req.params),ts=Date.now();app.db.prepare('UPDATE devices SET revoked_at=? WHERE id=?').run(ts,id);app.db.prepare('UPDATE sessions SET revoked_at=? WHERE device_id=?').run(ts,id);return {ok:true};});
  app.get('/api/settings',{preHandler:requireAuth(app,true)},async()=>readSettings(app));
  app.get('/api/settings/diagnostics',{preHandler:requireAuth(app,true)},async()=>runDiagnostics(app));
  app.post('/api/settings/diagnostics/ocr',{preHandler:requireAuth(app,true)},async()=>{const task=ocrDiagnosticRun??=runOcrDiagnostic(app);try{return await task;}finally{if(ocrDiagnosticRun===task)ocrDiagnosticRun=undefined;}});
  app.get('/api/settings/retention',{preHandler:requireAuth(app)},async()=>({imagesDays:retentionSetting(app,'images_days'),filesDays:retentionSetting(app,'files_days'),trashDays:retentionSetting(app,'trash_days'),downloadedEarlier:setting(app.db,'downloaded_earlier')==='true'}));
  app.patch('/api/settings',{preHandler:requireAuth(app,true)},async req=>{const b=z.object({ocrEnabled:z.boolean().optional(),retentionDays:retentionDaysSchema.optional(),storage:z.object({limit:z.number().int().positive().nullable().optional()}).optional(),retention:z.object({imagesDays:retentionDaysSchema.optional(),filesDays:retentionDaysSchema.optional(),trashDays:retentionDaysSchema.optional(),downloadedEarlier:z.boolean().optional()}).optional(),defaultShare:z.object({expiresIn:z.number().int().min(60).max(30*86400),maxDownloads:z.number().int().positive().max(10000).nullable().optional()}).optional(),branding:z.object({siteTitle:z.string().trim().min(1).max(24),tabTitle:z.string().trim().min(1).max(80)}).optional()}).parse(req.body);if(b.ocrEnabled!==undefined)setSetting(app.db,'ocr_enabled',String(b.ocrEnabled));const images=b.retention?.imagesDays??b.retentionDays,files=b.retention?.filesDays??b.retentionDays;if(images!==undefined)setSetting(app.db,'images_days',String(images));if(files!==undefined)setSetting(app.db,'files_days',String(files));if(b.retention?.trashDays!==undefined)setSetting(app.db,'trash_days',String(b.retention.trashDays));if(b.retention?.downloadedEarlier!==undefined)setSetting(app.db,'downloaded_earlier',String(b.retention.downloadedEarlier));if(b.storage?.limit!==undefined)setSetting(app.db,'storage_limit_bytes',String(b.storage.limit??0));if(b.defaultShare){setSetting(app.db,'default_share_expires',String(b.defaultShare.expiresIn));setSetting(app.db,'default_share_downloads',b.defaultShare.maxDownloads===null?'0':String(b.defaultShare.maxDownloads??1));}if(b.branding){setSetting(app.db,'site_title',b.branding.siteTitle);setSetting(app.db,'tab_title',b.branding.tabTitle);}return readSettings(app);});
  app.get('/api/settings/export',{preHandler:requireAuth(app,true)},async(_req,reply)=>{const snapshot=path.join(app.config.tempDir,`transfer-backup-${Date.now()}-${nanoid()}.sqlite`);await app.db.backup(snapshot);const cleanup=()=>void fs.rm(snapshot,{force:true}).catch(error=>app.log.warn({error},'failed to remove backup snapshot'));reply.raw.once('finish',cleanup);reply.raw.once('close',cleanup);return reply.header('Content-Type','application/vnd.sqlite3').header('Content-Disposition',`attachment; filename="transfer-backup-${new Date().toISOString().slice(0,10)}.sqlite"`).send(createReadStream(snapshot));});
  app.get('/api/ocr/status',{preHandler:requireAuth(app,true)},async()=>({enabled:setting(app.db,'ocr_enabled')!=='false',counts:app.db.prepare('SELECT j.status,count(*) AS count FROM ocr_jobs j JOIN messages m ON m.id=j.message_id WHERE m.deleted_at IS NULL GROUP BY j.status').all()}));
  app.get('/api/ocr/jobs',{preHandler:requireAuth(app,true)},async req=>{const q=z.object({status:z.enum(['done','pending','processing','failed']),limit:z.coerce.number().int().min(1).max(100).default(40),offset:z.coerce.number().int().min(0).default(0)}).parse(req.query),order=q.status==='pending'?'j.created_at ASC':'j.updated_at DESC',where="j.status=? AND m.deleted_at IS NULL",fields=`m.id,m.type,m.content,m.file_name AS fileName,m.mime,m.size,m.sha256,m.source_device_id AS sourceDeviceId,m.source_session_id AS sourceSessionId,m.source_name AS sourceDeviceName,m.visibility,m.favorite,m.pinned,m.created_at AS createdAt,m.updated_at AS updatedAt,m.ocr_text AS ocrText,m.ocr_status AS ocrStatus,m.tags,m.note,j.status AS jobStatus,j.attempts,j.error,j.updated_at AS jobUpdatedAt`;const total=(app.db.prepare(`SELECT count(*) AS count FROM ocr_jobs j JOIN messages m ON m.id=j.message_id WHERE ${where}`).get(q.status) as {count:number}).count,items=app.db.prepare(`SELECT ${fields} FROM ocr_jobs j JOIN messages m ON m.id=j.message_id WHERE ${where} ORDER BY ${order} LIMIT ? OFFSET ?`).all(q.status,q.limit,q.offset);const nextOffset=q.offset+items.length<total?q.offset+items.length:null;return {items,total,nextOffset};});
  app.post('/api/ocr/requeue',{preHandler:requireAuth(app,true)},async req=>{const b=z.object({scope:z.enum(['all','failed']).default('failed'),messageId:z.string().optional()}).parse(req.body);return {ok:true,queued:requeueOcr(app,b)};});
  app.post('/api/ocr/reindex',{preHandler:requireAuth(app,true)},async req=>{const b=z.object({scope:z.enum(['all','failed']).default('failed'),messageId:z.string().optional()}).parse(req.body);return {ok:true,queued:requeueOcr(app,b)};});
  app.get('/api/ocr/jobs/next',{preHandler:requireAuth(app,true)},async()=>{if(setting(app.db,'ocr_enabled')==='false')return {job:null};const job=app.db.prepare("SELECT j.id,j.message_id AS messageId,b.path,m.mime FROM ocr_jobs j JOIN messages m ON m.id=j.message_id JOIN blobs b ON b.id=m.blob_id WHERE j.status='pending' AND m.deleted_at IS NULL ORDER BY j.created_at LIMIT 1").get() as {id:string}|undefined;if(job)app.db.prepare("UPDATE ocr_jobs SET status='processing',attempts=attempts+1,updated_at=? WHERE id=?").run(Date.now(),job.id);return {job:job??null};});
  app.post('/api/ocr/jobs/:id/complete',{preHandler:requireAuth(app,true)},async(req,reply)=>{const {id}=z.object({id:z.string()}).parse(req.params);const b=z.object({text:z.string().max(5_000_000).optional(),error:z.string().max(2000).optional()}).parse(req.body);const job=app.db.prepare('SELECT message_id FROM ocr_jobs WHERE id=?').get(id) as {message_id:string}|undefined;if(!job)return reply.code(404).send({error:'not_found'});if(b.error){app.db.prepare("UPDATE ocr_jobs SET status='failed',error=?,updated_at=? WHERE id=?").run(b.error,Date.now(),id);app.db.prepare("UPDATE messages SET ocr_status='failed' WHERE id=?").run(job.message_id);}else{app.db.prepare("UPDATE ocr_jobs SET status='done',error=NULL,updated_at=? WHERE id=?").run(Date.now(),id);app.db.prepare("UPDATE messages SET ocr_text=?,ocr_status='done',updated_at=? WHERE id=?").run(b.text??'',Date.now(),job.message_id);indexMessage(app.db,job.message_id);}return {ok:true};});
  app.post('/api/ocr/messages/:id/requeue',{preHandler:requireAuth(app,true)},async req=>{const {id}=z.object({id:z.string()}).parse(req.params);return {ok:true,queued:requeueOcr(app,{messageId:id})};});
}
