import type { FastifyInstance } from 'fastify';
import { z } from 'zod';
import { nanoid } from 'nanoid';
import { promises as fs } from 'node:fs';
import { indexMessage, setting } from './db.js';
import { requireAuth } from './auth.js';
import { passwordVerify } from './security.js';

const fields = `m.id,m.type,m.content,m.file_name AS fileName,m.mime,m.size,m.sha256,m.source_device_id AS sourceDeviceId,m.source_session_id AS sourceSessionId,m.source_name AS sourceDeviceName,m.visibility,m.favorite,m.pinned,m.deleted_at AS deletedAt,m.created_at AS createdAt,m.updated_at AS updatedAt,m.ocr_status AS ocrStatus,m.tags,m.note`;
const visibleSql = (trusted:boolean, deviceId?:string) => `${trusted?'1=1':"m.visibility='normal'"} AND (NOT EXISTS(SELECT 1 FROM message_targets mt WHERE mt.message_id=m.id) ${deviceId?'OR m.source_device_id=@deviceId OR EXISTS(SELECT 1 FROM message_targets mt WHERE mt.message_id=m.id AND mt.device_id=@deviceId)':''})`;
const audience=(app:FastifyInstance,id:string,source?:string)=>[...new Set([...(app.db.prepare('SELECT device_id FROM message_targets WHERE message_id=?').all(id) as {device_id:string}[]).map(x=>x.device_id),...(source?[source]:[])])];
const queryBoolean=z.preprocess(v=>typeof v==='string'?(v==='true'||v==='1'?true:v==='false'||v==='0'?false:v):v,z.boolean());

export async function purgeDeleted(app:FastifyInstance,before:number,limit?:number){
  const removed=app.db.transaction(()=>{const rows=app.db.prepare(`SELECT id,blob_id AS blobId FROM messages WHERE deleted_at IS NOT NULL AND deleted_at<=? ORDER BY deleted_at${limit?' LIMIT ?':''}`).all(...(limit?[before,limit]:[before])) as {id:string;blobId?:string}[];for(const row of rows){app.db.prepare('DELETE FROM messages_fts WHERE message_id=?').run(row.id);app.db.prepare('DELETE FROM shares WHERE message_id=? OR id IN (SELECT share_id FROM share_messages WHERE message_id=?)').run(row.id,row.id);}const remove=app.db.prepare('DELETE FROM messages WHERE id=?');for(const row of rows)remove.run(row.id);for(const row of rows)if(row.blobId)app.db.prepare('UPDATE blobs SET ref_count=ref_count-1 WHERE id=?').run(row.blobId);const orphaned=app.db.prepare('SELECT id,path FROM blobs WHERE ref_count<=0').all() as {id:string;path:string}[];for(const blob of orphaned)app.db.prepare('DELETE FROM blobs WHERE id=?').run(blob.id);return {messages:rows.length,orphaned};})();for(const blob of removed.orphaned)await fs.rm(blob.path,{force:true}).catch(error=>app.log.warn({error,blobId:blob.id},'failed to remove orphaned blob'));return {deletedMessages:removed.messages,deletedBlobs:removed.orphaned.length};
}

async function purgeMessage(app:FastifyInstance,id:string){
  const removed=app.db.transaction(()=>{const row=app.db.prepare('SELECT blob_id AS blobId FROM messages WHERE id=?').get(id) as {blobId?:string}|undefined;if(!row)return;app.db.prepare('DELETE FROM messages_fts WHERE message_id=?').run(id);app.db.prepare('DELETE FROM shares WHERE message_id=? OR id IN (SELECT share_id FROM share_messages WHERE message_id=?)').run(id,id);app.db.prepare('DELETE FROM messages WHERE id=?').run(id);if(!row.blobId)return {path:undefined};app.db.prepare('UPDATE blobs SET ref_count=ref_count-1 WHERE id=?').run(row.blobId);const blob=app.db.prepare('SELECT path FROM blobs WHERE id=? AND ref_count<=0').get(row.blobId) as {path:string}|undefined;if(blob)app.db.prepare('DELETE FROM blobs WHERE id=?').run(row.blobId);return blob;})();if(removed?.path)await fs.rm(removed.path,{force:true}).catch(error=>app.log.warn({error,messageId:id},'failed to remove message blob'));return Boolean(removed);
}

function one(app:FastifyInstance,id:string,trusted:boolean,deviceId?:string,includeDeleted=false){
  return app.db.prepare(`SELECT ${fields} FROM messages m WHERE m.id=@id AND ${includeDeleted?'1=1':'m.deleted_at IS NULL'} AND ${visibleSql(trusted,deviceId)}`).get({id,deviceId}) as Record<string,unknown>|undefined;
}

export async function messageRoutes(app: FastifyInstance) {
  app.get('/api/messages',{preHandler:requireAuth(app)},async req=>{
    const q=z.object({cursor:z.coerce.number().optional(),limit:z.coerce.number().int().min(1).max(100).default(50),favorite:queryBoolean.optional(),pinned:queryBoolean.optional(),trash:queryBoolean.default(false),deviceId:z.string().optional()}).parse(req.query);
    const p=req.principal!, where=[q.trash?'m.deleted_at IS NOT NULL':'m.deleted_at IS NULL',visibleSql(p.kind==='device',p.deviceId)];
    if(q.cursor)where.push('m.created_at<@cursor');if(q.favorite!==undefined)where.push('m.favorite=@favorite');if(q.pinned!==undefined)where.push('m.pinned=@pinned');if(q.deviceId)where.push('m.source_device_id=@sourceFilter');
    const items=app.db.prepare(`SELECT ${fields} FROM messages m WHERE ${where.join(' AND ')} ORDER BY m.pinned DESC,m.created_at DESC LIMIT @limit`).all({cursor:q.cursor,favorite:Number(q.favorite),pinned:Number(q.pinned),deviceId:p.deviceId,sourceFilter:q.deviceId,limit:q.limit});
    return {items,nextCursor:(items.at(-1) as {createdAt?:number}|undefined)?.createdAt ?? null};
  });
  app.get('/api/messages/:id',{preHandler:requireAuth(app)},async(req,reply)=>{const {id}=z.object({id:z.string()}).parse(req.params);const item=one(app,id,req.principal!.kind==='device',req.principal!.deviceId);return item??reply.code(404).send({error:'not_found'});});
  app.get('/api/messages/:id/history',{preHandler:requireAuth(app)},async(req,reply)=>{const {id}=z.object({id:z.string()}).parse(req.params);if(!one(app,id,req.principal!.kind==='device',req.principal!.deviceId,true))return reply.code(404).send({error:'not_found'});return {items:app.db.prepare('SELECT id,previous_content AS content,editor_device_id AS editorDeviceId,created_at AS createdAt FROM message_history WHERE message_id=? ORDER BY created_at DESC LIMIT 100').all(id)};});
  app.post('/api/messages',{preHandler:requireAuth(app)},async(req,reply)=>{
    const b=z.object({content:z.string().min(1).max(1_000_000),visibility:z.enum(['normal','trusted_only']).default('normal'),targetDeviceIds:z.array(z.string()).max(50).default([]),tags:z.array(z.string().max(40)).max(20).default([]),note:z.string().max(1000).default('')}).parse(req.body);
    if(b.visibility==='trusted_only'&&req.principal!.kind!=='device')return reply.code(403).send({error:'trusted_device_required'});
    const id=nanoid(),ts=Date.now();const tx=app.db.transaction(()=>{app.db.prepare(`INSERT INTO messages(id,type,content,source_device_id,source_session_id,source_name,visibility,created_at,updated_at,tags,note) VALUES(?,?,?,?,?,?,?,?,?,?,?)`).run(id,'text',b.content,req.principal!.deviceId??null,req.principal!.sessionId,req.principal!.name,b.visibility,ts,ts,JSON.stringify(b.tags),b.note);for(const d of b.targetDeviceIds)app.db.prepare('INSERT INTO message_targets(message_id,device_id) VALUES(?,?)').run(id,d);indexMessage(app.db,id);});tx();
    const item=one(app,id,true,req.principal!.deviceId)!;app.broadcast({type:'message.created',message:item},b.visibility==='trusted_only',b.targetDeviceIds.length?audience(app,id,req.principal!.deviceId):undefined);return reply.code(201).send(item);
  });
  app.patch('/api/messages/:id',{preHandler:requireAuth(app)},async(req,reply)=>{
    const {id}=z.object({id:z.string()}).parse(req.params);const b=z.object({content:z.string().min(1).max(1_000_000).optional(),favorite:z.boolean().optional(),pinned:z.boolean().optional(),visibility:z.enum(['normal','trusted_only']).optional(),tags:z.array(z.string().max(40)).max(20).optional(),note:z.string().max(1000).optional()}).parse(req.body);
    const old=one(app,id,req.principal!.kind==='device',req.principal!.deviceId);if(!old)return reply.code(404).send({error:'not_found'});if(b.visibility!==undefined&&req.principal!.kind!=='device')return reply.code(403).send({error:'trusted_device_required'});
    const sets:string[]=['updated_at=@updated'];const vals:Record<string,unknown>={id,updated:Date.now()};for(const [key,col] of Object.entries({content:'content',favorite:'favorite',pinned:'pinned',visibility:'visibility',tags:'tags',note:'note'})){const v=b[key as keyof typeof b];if(v!==undefined){sets.push(`${col}=@${key}`);vals[key]=Array.isArray(v)?JSON.stringify(v):typeof v==='boolean'?Number(v):v;}}
    if(b.content!==undefined&&b.content!==old.content)app.db.prepare('INSERT INTO message_history(id,message_id,previous_content,editor_device_id,created_at) VALUES(?,?,?,?,?)').run(nanoid(),id,String(old.content??''),req.principal!.deviceId??null,Date.now());app.db.prepare(`UPDATE messages SET ${sets.join(',')} WHERE id=@id`).run(vals);indexMessage(app.db,id);const item=one(app,id,true,req.principal!.deviceId)!;const targets=audience(app,id,String(item.sourceDeviceId??''));app.broadcast({type:'message.updated',message:item},item.visibility==='trusted_only',targets.length?targets:undefined);if(old.visibility==='normal'&&item.visibility==='trusted_only')app.broadcast({type:'message.hidden',id},false,undefined,true);return item;
  });
  app.delete('/api/messages/:id',{preHandler:requireAuth(app)},async(req,reply)=>{const {id}=z.object({id:z.string()}).parse(req.params),{permanent}=z.object({permanent:queryBoolean.default(false)}).parse(req.query);if(!one(app,id,req.principal!.kind==='device',req.principal!.deviceId,permanent))return reply.code(404).send({error:'not_found'});if(permanent){await purgeMessage(app,id);app.broadcast({type:'message.deleted',id});return {ok:true,permanent:true};}const ts=Date.now();app.db.transaction(()=>{app.db.prepare('UPDATE messages SET deleted_at=?,updated_at=? WHERE id=?').run(ts,ts,id);app.db.prepare('UPDATE shares SET revoked_at=? WHERE (message_id=? OR id IN (SELECT share_id FROM share_messages WHERE message_id=?)) AND revoked_at IS NULL').run(ts,id,id);})();app.broadcast({type:'message.deleted',id});return {ok:true};});
  app.post('/api/messages/:id/restore',{preHandler:requireAuth(app)},async(req,reply)=>{const {id}=z.object({id:z.string()}).parse(req.params);if(!one(app,id,req.principal!.kind==='device',req.principal!.deviceId,true))return reply.code(404).send({error:'not_found'});app.db.prepare('UPDATE messages SET deleted_at=NULL,updated_at=? WHERE id=?').run(Date.now(),id);return {ok:true};});
  app.post('/api/messages/merge',{preHandler:requireAuth(app)},async(req,reply)=>{const {ids}=z.object({ids:z.array(z.string()).min(2).max(50)}).parse(req.body),principal=req.principal!,unique=[...new Set(ids)];if(unique.length<2)return reply.code(400).send({error:'merge_requires_multiple'});const items=unique.map(id=>one(app,id,principal.kind==='device',principal.deviceId)).filter(Boolean) as Record<string,unknown>[];if(items.length!==unique.length)return reply.code(404).send({error:'not_found'});if(items.some(item=>item.type!=='text'))return reply.code(400).send({error:'merge_text_only'});const targeted=app.db.prepare(`SELECT count(*) AS count FROM message_targets WHERE message_id IN (${unique.map(()=>'?').join(',')})`).get(...unique) as {count:number};if(targeted.count)return reply.code(400).send({error:'merge_targeted_not_supported'});items.sort((a,b)=>Number(a.createdAt)-Number(b.createdAt));const target=items[0],targetId=String(target.id),mergedIds=items.slice(1).map(item=>String(item.id)),content=items.map(item=>String(item.content??'')).join('\n');if(content.length>1_000_000)return reply.code(400).send({error:'merged_content_too_large'});const visibility=items.some(item=>item.visibility==='trusted_only')?'trusted_only':'normal';if(visibility==='trusted_only'&&principal.kind!=='device')return reply.code(403).send({error:'trusted_device_required'});const favorite=items.some(item=>Boolean(item.favorite)),pinned=items.some(item=>Boolean(item.pinned)),tags=[...new Set(items.flatMap(item=>{try{return JSON.parse(String(item.tags??'[]')) as string[]}catch{return []}}))],notes=items.map(item=>String(item.note??'').trim()).filter(Boolean),note=[...new Set(notes)].join('\n'),ts=Date.now();app.db.transaction(()=>{app.db.prepare('INSERT INTO message_history(id,message_id,previous_content,editor_device_id,created_at) VALUES(?,?,?,?,?)').run(nanoid(),targetId,String(target.content??''),principal.deviceId??null,ts);app.db.prepare('UPDATE messages SET content=?,visibility=?,favorite=?,pinned=?,tags=?,note=?,updated_at=? WHERE id=?').run(content,visibility,Number(favorite),Number(pinned),JSON.stringify(tags),note,ts,targetId);const placeholders=mergedIds.map(()=>'?').join(',');app.db.prepare(`UPDATE messages SET deleted_at=?,updated_at=? WHERE id IN (${placeholders})`).run(ts,ts,...mergedIds);app.db.prepare(`UPDATE shares SET revoked_at=? WHERE (message_id IN (${placeholders}) OR id IN (SELECT share_id FROM share_messages WHERE message_id IN (${placeholders}))) AND revoked_at IS NULL`).run(ts,...mergedIds,...mergedIds);indexMessage(app.db,targetId);})();const item=one(app,targetId,true,principal.deviceId)!;for(const oldId of mergedIds)app.broadcast({type:'message.deleted',id:oldId});app.broadcast({type:'message.updated',message:item},visibility==='trusted_only');return item;});
  app.post('/api/messages/batch',{preHandler:requireAuth(app)},async(req,reply)=>{const b=z.object({ids:z.array(z.string()).min(1).max(200),action:z.enum(['delete','restore','purge','favorite','unfavorite','pin','unpin','lock','unlock'])}).parse(req.body);if(['lock','unlock'].includes(b.action)&&req.principal!.kind!=='device')return reply.code(403).send({error:'trusted_device_required'});const includeDeleted=['restore','purge'].includes(b.action),ids=[...new Set(b.ids)].filter(id=>{const item=one(app,id,req.principal!.kind==='device',req.principal!.deviceId,includeDeleted);return Boolean(item)&&(b.action!=='purge'||item!.deletedAt!=null);});if(!ids.length)return {updated:0};if(b.action==='purge'){let updated=0;for(const id of ids)if(await purgeMessage(app,id)){updated+=1;app.broadcast({type:'message.deleted',id});}return {updated};}const map:Record<string,string>={delete:'deleted_at=?',restore:'deleted_at=NULL',favorite:'favorite=1',unfavorite:'favorite=0',pin:'pinned=1',unpin:'pinned=0',lock:"visibility='trusted_only'",unlock:"visibility='normal'"},placeholders=ids.map(()=>'?').join(','),ts=Date.now(),params=b.action==='delete'?[ts,...ids]:ids;const info=app.db.transaction(()=>{const result=app.db.prepare(`UPDATE messages SET ${map[b.action]},updated_at=${ts} WHERE id IN (${placeholders})`).run(...params);if(b.action==='delete')app.db.prepare(`UPDATE shares SET revoked_at=? WHERE (message_id IN (${placeholders}) OR id IN (SELECT share_id FROM share_messages WHERE message_id IN (${placeholders}))) AND revoked_at IS NULL`).run(ts,...ids,...ids);return result;})();for(const id of ids){if(b.action==='lock')app.broadcast({type:'message.hidden',id},false,undefined,true);else app.broadcast({type:'message.updated',id});}return {updated:info.changes};});
  app.delete('/api/trash',{preHandler:requireAuth(app,true)},async(req,reply)=>{const {adminPassword}=z.object({adminPassword:z.string()}).parse(req.body);if(!await passwordVerify(setting(app.db,'admin_password_hash'),adminPassword))return reply.code(401).send({error:'invalid_admin_password'});return {ok:true,...await purgeDeleted(app,Date.now())};});
}

export { one as visibleMessage };
