import type { FastifyReply } from 'fastify';
import { createReadStream } from 'node:fs';

export type PreviewFile={fileName:string;path:string;mime:string;size:number};

export function attachmentDisposition(fileName:string){const fallback=fileName.replace(/[^\x20-\x7E]/g,'_').replace(/["\\]/g,'_')||'download';return `attachment; filename="${fallback}"; filename*=UTF-8''${encodeURIComponent(fileName)}`;}
export function inlineDisposition(fileName:string){return attachmentDisposition(fileName).replace(/^attachment/,'inline');}
export function previewMime(fileName:string,storedMime:string){const mime=storedMime.split(';')[0].trim().toLowerCase();if(mime.startsWith('image/')||mime.startsWith('video/')||mime.startsWith('audio/')||mime==='application/pdf'||mime==='text/html'||mime==='application/xhtml+xml')return mime;if(mime.startsWith('text/'))return 'text/plain; charset=utf-8';if(['application/json','application/xml','application/javascript'].includes(mime))return 'text/plain; charset=utf-8';const ext=fileName.toLowerCase().split('.').pop()??'',fallback:Record<string,string>={jpg:'image/jpeg',jpeg:'image/jpeg',png:'image/png',gif:'image/gif',webp:'image/webp',avif:'image/avif',bmp:'image/bmp',svg:'image/svg+xml',pdf:'application/pdf',mp4:'video/mp4',webm:'video/webm',mov:'video/quicktime',m4v:'video/x-m4v',mp3:'audio/mpeg',m4a:'audio/mp4',wav:'audio/wav',ogg:'audio/ogg',html:'text/html',htm:'text/html',txt:'text/plain; charset=utf-8',md:'text/plain; charset=utf-8',csv:'text/plain; charset=utf-8',log:'text/plain; charset=utf-8',json:'text/plain; charset=utf-8',xml:'text/plain; charset=utf-8'};return fallback[ext];}
function byteRange(header:string|undefined,size:number){if(!header)return undefined;const match=/^bytes=(\d*)-(\d*)$/.exec(header.trim());if(!match)return null;let start:number,end:number;if(!match[1]){const length=Number(match[2]);if(!Number.isSafeInteger(length)||length<=0)return null;start=Math.max(0,size-length);end=size-1;}else{start=Number(match[1]);end=match[2]?Number(match[2]):size-1;if(!Number.isSafeInteger(start)||!Number.isSafeInteger(end)||start<0||end<start||start>=size)return null;end=Math.min(end,size-1);}return {start,end};}
export function streamInlinePreview(reply:FastifyReply,rangeHeader:string|undefined,file:PreviewFile){const mime=previewMime(file.fileName,file.mime);if(!mime)return reply.code(415).send({error:'preview_not_supported'});reply.header('Content-Type',mime).header('Content-Disposition',inlineDisposition(file.fileName)).header('Accept-Ranges','bytes').header('Cache-Control','private, no-store').header('Content-Security-Policy',"sandbox; default-src 'none'; img-src data: blob:; media-src data: blob:; style-src 'unsafe-inline'");if(file.size===0)return reply.header('Content-Length',0).send(Buffer.alloc(0));const range=byteRange(rangeHeader,file.size);if(range===null)return reply.code(416).header('Content-Range',`bytes */${file.size}`).send();const start=range?.start??0,end=range?.end??file.size-1,length=end-start+1;reply.header('Content-Length',length);if(range)reply.code(206).header('Content-Range',`bytes ${start}-${end}/${file.size}`);return reply.send(createReadStream(file.path,{start,end}));}
