import type { FastifyInstance } from 'fastify';
import { createReadStream } from 'node:fs';
import { nanoid } from 'nanoid';
import { z } from 'zod';
import { requireAuth } from './auth.js';
import { newToken, passwordHash, passwordVerify, sha256 } from './security.js';
import { markMessageDownloaded, saveUpload } from './files.js';
import { visibleMessage } from './messages.js';
import { setting } from './db.js';

const now=()=>Date.now();
async function reserveShareDownload(app:FastifyInstance,token:string,code?:string){
  const candidate=app.db.prepare(`SELECT id,code_hash AS codeHash FROM shares WHERE token_hash=? AND revoked_at IS NULL AND expires_at>?`).get(sha256(token),now()) as {id:string;codeHash?:string}|undefined;
  if(!candidate)return {error:'not_found'} as const;
  if(candidate.codeHash&&!code)return {error:'code_required'} as const;
  if(candidate.codeHash&&!await passwordVerify(candidate.codeHash,code!))return {error:'invalid_code'} as const;
  const reserved=app.db.prepare(`UPDATE shares SET downloads=downloads+1 WHERE id=? AND revoked_at IS NULL AND expires_at>? AND (max_downloads IS NULL OR downloads<max_downloads) RETURNING message_id AS messageId`).get(candidate.id,now()) as {messageId:string}|undefined;
  return reserved??({error:'not_found'} as const);
}

function reserveDrop(app:FastifyInstance,token:string){
  return app.db.prepare(`UPDATE drops SET uploads=uploads+1 WHERE token_hash=? AND revoked_at IS NULL AND expires_at>? AND (max_uploads IS NULL OR uploads<max_uploads) RETURNING id`).get(sha256(token),now()) as {id:string}|undefined;
}

export async function sharingRoutes(app:FastifyInstance){
  app.post('/api/shares',{preHandler:requireAuth(app)},async(req,reply)=>{const b=z.object({messageId:z.string(),expiresInSeconds:z.number().int().min(60).max(30*86400).optional(),expiresIn:z.number().int().min(60).max(30*86400).optional(),maxDownloads:z.number().int().positive().max(10000).nullable().optional(),code:z.string().min(4).max(100).optional()}).parse(req.body);const ttl=b.expiresInSeconds??b.expiresIn??Number(setting(app.db,'default_share_expires')??3600),configured=setting(app.db,'default_share_downloads'),maxDownloads=b.maxDownloads!==undefined?b.maxDownloads:configured===undefined?1:Number(configured)||null;const msg=visibleMessage(app,b.messageId,req.principal!.kind==='device',req.principal!.deviceId);if(!msg)return reply.code(404).send({error:'not_found'});if(msg.visibility==='trusted_only'&&req.principal!.kind!=='device')return reply.code(403).send({error:'trusted_device_required'});const token=newToken(),id=nanoid();app.db.prepare('INSERT INTO shares VALUES(?,?,?,?,?,?,0,NULL,?)').run(id,sha256(token),b.messageId,b.code?await passwordHash(b.code):null,now()+ttl*1000,maxDownloads,now());return reply.code(201).send({id,token,expiresAt:now()+ttl*1000,maxDownloads});});
  app.get('/api/shares',{preHandler:requireAuth(app,true)},async()=>({items:app.db.prepare(`SELECT s.id,s.message_id AS messageId,s.expires_at AS expiresAt,s.max_downloads AS maxDownloads,s.downloads,s.revoked_at AS revokedAt,s.created_at AS createdAt,m.file_name AS fileName,m.type FROM shares s JOIN messages m ON m.id=s.message_id ORDER BY s.created_at DESC`).all()}));
  app.delete('/api/shares/:id',{preHandler:requireAuth(app,true)},async(req)=>{const {id}=z.object({id:z.string()}).parse(req.params);app.db.prepare('UPDATE shares SET revoked_at=? WHERE id=?').run(now(),id);return {ok:true};});
  app.post('/api/public/shares/:token',async(req,reply)=>{const {token}=z.object({token:z.string()}).parse(req.params);const {code}=z.object({code:z.string().optional()}).parse(req.body??{});const s=app.db.prepare(`SELECT * FROM shares WHERE token_hash=? AND revoked_at IS NULL AND expires_at>? AND (max_downloads IS NULL OR downloads<max_downloads)`).get(sha256(token),now()) as {id:string;message_id:string;code_hash?:string}|undefined;if(!s)return reply.code(404).send({error:'not_found'});if(s.code_hash&&!code)return reply.code(401).send({error:'code_required'});if(s.code_hash&&!await passwordVerify(s.code_hash,code!))return reply.code(401).send({error:'invalid_code'});const m=app.db.prepare('SELECT id,type,content,file_name AS fileName,mime,size FROM messages WHERE id=? AND deleted_at IS NULL').get(s.message_id) as Record<string,unknown>|undefined;if(!m)return reply.code(404).send({error:'not_found'});return m;});
  app.get('/api/public/shares/:token',async(req,reply)=>{const {token}=z.object({token:z.string()}).parse(req.params);const {code}=z.object({code:z.string().optional()}).parse(req.query);const s=app.db.prepare(`SELECT * FROM shares WHERE token_hash=? AND revoked_at IS NULL AND expires_at>? AND (max_downloads IS NULL OR downloads<max_downloads)`).get(sha256(token),now()) as {message_id:string;code_hash?:string}|undefined;if(!s)return reply.code(404).send({error:'not_found'});if(s.code_hash&&!await passwordVerify(s.code_hash,code??''))return reply.code(401).send({error:code?'invalid_code':'code_required'});const message=app.db.prepare('SELECT id,type,content,file_name AS fileName,mime,size FROM messages WHERE id=? AND deleted_at IS NULL').get(s.message_id);return message?{message}:reply.code(404).send({error:'not_found'});});
  app.get('/api/public/shares/:token/download',async(req,reply)=>{const {token}=z.object({token:z.string()}).parse(req.params);const q=z.object({code:z.string().optional()}).parse(req.query);const reserved=await reserveShareDownload(app,token,q.code);if('error'in reserved)return reply.code(reserved.error==='not_found'?404:401).send({error:reserved.error});const m=app.db.prepare('SELECT m.file_name,b.path,b.mime,b.size FROM messages m JOIN blobs b ON b.id=m.blob_id WHERE m.id=? AND m.deleted_at IS NULL').get(reserved.messageId) as {file_name:string;path:string;mime:string;size:number}|undefined;if(!m)return reply.code(404).send({error:'not_found'});markMessageDownloaded(app,reserved.messageId);return reply.header('Content-Type',m.mime).header('Content-Length',m.size).header('Content-Disposition',`attachment; filename*=UTF-8''${encodeURIComponent(m.file_name)}`).send(createReadStream(m.path));});
  app.post('/api/drops',{preHandler:requireAuth(app,true)},async(req,reply)=>{const b=z.object({name:z.string().min(1).max(80),expiresInSeconds:z.number().int().min(60).max(30*86400).optional(),expiresIn:z.number().int().min(60).max(30*86400).optional(),maxUploads:z.number().int().positive().max(10000).nullable().default(null),maxFileSize:z.number().int().positive().nullable().default(null),allowedTypes:z.array(z.string()).max(30).default([])}).parse(req.body);const ttl=b.expiresInSeconds??b.expiresIn??86400;const token=newToken(),id=nanoid();app.db.prepare('INSERT INTO drops(id,token_hash,name,expires_at,max_uploads,uploads,max_file_size,allowed_types,revoked_at,created_at) VALUES(?,?,?,?,?,0,?,?,NULL,?)').run(id,sha256(token),b.name,now()+ttl*1000,b.maxUploads,b.maxFileSize,JSON.stringify(b.allowedTypes),now());return reply.code(201).send({id,token,expiresAt:now()+ttl*1000});});
  app.get('/api/drops',{preHandler:requireAuth(app,true)},async()=>({items:app.db.prepare('SELECT id,name,expires_at AS expiresAt,max_uploads AS maxUploads,uploads,max_file_size AS maxFileSize,allowed_types AS allowedTypes,revoked_at AS revokedAt,created_at AS createdAt FROM drops ORDER BY created_at DESC').all()}));
  app.delete('/api/drops/:id',{preHandler:requireAuth(app,true)},async req=>{const {id}=z.object({id:z.string()}).parse(req.params);app.db.prepare('UPDATE drops SET revoked_at=? WHERE id=?').run(now(),id);return {ok:true};});
  app.get('/api/public/drops/:token',async(req,reply)=>{const {token}=z.object({token:z.string()}).parse(req.params);const d=app.db.prepare('SELECT name,expires_at AS expiresAt,max_file_size AS maxFileSize,allowed_types AS allowedTypes FROM drops WHERE token_hash=? AND revoked_at IS NULL AND expires_at>? AND (max_uploads IS NULL OR uploads<max_uploads)').get(sha256(token),now());return d?{drop:d}:reply.code(404).send({error:'not_found'});});
  const receiveDrop=async(req:any,reply:any)=>{const {token}=z.object({token:z.string()}).parse(req.params);const d=reserveDrop(app,token);if(!d)return reply.code(404).send({error:'not_found'});try{const item=await saveUpload(app,req,false,d.id);app.broadcast({type:'message.created',message:item});return reply.code(201).send({ok:true,messageId:item.id});}catch(error){app.db.prepare('UPDATE drops SET uploads=MAX(uploads-1,0) WHERE id=?').run(d.id);throw error;}};
  app.post('/api/public/drops/:token/upload',receiveDrop);
  app.post('/api/public/drops/:token',receiveDrop);
}
