import type { FastifyInstance } from 'fastify';
import { createReadStream } from 'node:fs';
import { nanoid } from 'nanoid';
import { z } from 'zod';
import { requireAuth } from './auth.js';
import { newToken, passwordHash, passwordVerify, sha256 } from './security.js';
import { markMessageDownloaded, saveUpload } from './files.js';
import { visibleMessage } from './messages.js';
import { setting } from './db.js';
import { attachmentDisposition, streamInlinePreview } from './preview.js';

const now=()=>Date.now();
const shareExpiry=z.number().int().min(60).max(30*86400).nullable();
const shareDownloadLimit=z.number().int().positive().max(10000).nullable();
const dropExpiry=z.number().int().min(60).max(30*86400);
const dropUploadLimit=z.number().int().positive().max(10000).nullable();
const dropFileLimit=z.number().int().positive().max(20*1024*1024*1024).nullable();
const dropTypes=z.array(z.string().min(1).max(120)).max(30);
const activeExpiry='(expires_at=0 OR expires_at>?)';
const expiryFromTtl=(ttl:number|null)=>ttl===null?0:now()+ttl*1000;
const publicMessageFields='m.id,m.type,m.content,m.file_name AS fileName,m.mime,m.size,m.created_at AS createdAt';
const messagesForShare=(app:FastifyInstance,shareId:string)=>app.db.prepare(`SELECT ${publicMessageFields} FROM share_messages sm JOIN messages m ON m.id=sm.message_id WHERE sm.share_id=? AND m.deleted_at IS NULL ORDER BY sm.position,m.created_at`).all(shareId) as Record<string,unknown>[];
async function sharedFile(app:FastifyInstance,token:string,code?:string,requestedMessageId?:string){const share=app.db.prepare(`SELECT id,message_id AS messageId,code_hash AS codeHash FROM shares WHERE token_hash=? AND revoked_at IS NULL AND ${activeExpiry} AND (max_downloads IS NULL OR downloads<max_downloads)`).get(sha256(token),now()) as {id:string;messageId:string;codeHash?:string}|undefined;if(!share)return {error:'not_found'} as const;if(share.codeHash&&!code)return {error:'code_required'} as const;if(share.codeHash&&!await passwordVerify(share.codeHash,code!))return {error:'invalid_code'} as const;const messageId=requestedMessageId??share.messageId,member=app.db.prepare('SELECT 1 FROM share_messages WHERE share_id=? AND message_id=?').get(share.id,messageId);if(!member)return {error:'not_found'} as const;const file=app.db.prepare('SELECT m.file_name AS fileName,b.path,b.mime,b.size FROM messages m JOIN blobs b ON b.id=m.blob_id WHERE m.id=? AND m.deleted_at IS NULL').get(messageId) as {fileName:string;path:string;mime:string;size:number}|undefined;return file?{file}:({error:'not_found'} as const);}
async function reserveShareDownload(app:FastifyInstance,token:string,code?:string,requestedMessageId?:string){
  const candidate=app.db.prepare(`SELECT id,message_id AS messageId,code_hash AS codeHash FROM shares WHERE token_hash=? AND revoked_at IS NULL AND ${activeExpiry}`).get(sha256(token),now()) as {id:string;messageId:string;codeHash?:string}|undefined;
  if(!candidate)return {error:'not_found'} as const;
  if(candidate.codeHash&&!code)return {error:'code_required'} as const;
  if(candidate.codeHash&&!await passwordVerify(candidate.codeHash,code!))return {error:'invalid_code'} as const;
  const messageId=requestedMessageId??candidate.messageId;if(!app.db.prepare('SELECT 1 FROM share_messages WHERE share_id=? AND message_id=?').get(candidate.id,messageId))return {error:'not_found'} as const;
  const reserved=app.db.prepare(`UPDATE shares SET downloads=downloads+1 WHERE id=? AND revoked_at IS NULL AND ${activeExpiry} AND (max_downloads IS NULL OR downloads<max_downloads) RETURNING id`).get(candidate.id,now());
  return reserved?{messageId}:({error:'not_found'} as const);
}

function reserveDrop(app:FastifyInstance,token:string){
  return app.db.prepare(`UPDATE drops SET uploads=uploads+1 WHERE token_hash=? AND revoked_at IS NULL AND expires_at>? AND (max_uploads IS NULL OR uploads<max_uploads) RETURNING id`).get(sha256(token),now()) as {id:string}|undefined;
}

const managedDropFields='id,token_value AS token,name,expires_at AS expiresAt,max_uploads AS maxUploads,uploads,max_file_size AS maxFileSize,allowed_types AS allowedTypes,revoked_at AS revokedAt,created_at AS createdAt';
function normalizeDrop<T extends {allowedTypes?:string}>(drop:T){let allowedTypes:string[]=[];try{allowedTypes=JSON.parse(drop.allowedTypes??'[]') as string[];}catch{allowedTypes=[];}return {...drop,allowedTypes};}
function managedDrop(app:FastifyInstance,id:string){const drop=app.db.prepare(`SELECT ${managedDropFields} FROM drops WHERE id=?`).get(id) as {allowedTypes:string}|undefined;return drop?normalizeDrop(drop):undefined;}

export async function sharingRoutes(app:FastifyInstance){
  app.post('/api/shares',{preHandler:requireAuth(app)},async(req,reply)=>{const b=z.object({messageId:z.string().optional(),messageIds:z.array(z.string()).min(1).max(100).optional(),expiresInSeconds:shareExpiry.optional(),expiresIn:shareExpiry.optional(),maxDownloads:shareDownloadLimit.optional(),code:z.string().min(4).max(100).optional()}).refine(value=>Boolean(value.messageId||value.messageIds?.length)).parse(req.body),messageIds=[...new Set(b.messageIds??(b.messageId?[b.messageId]:[]))],principal=req.principal!,messages=messageIds.map(messageId=>visibleMessage(app,messageId,principal.kind==='device',principal.deviceId)).filter(Boolean) as Record<string,unknown>[];if(messages.length!==messageIds.length)return reply.code(404).send({error:'not_found'});if(messages.some(message=>message.visibility==='trusted_only')&&principal.kind!=='device')return reply.code(403).send({error:'trusted_device_required'});const suppliedTtl=b.expiresInSeconds!==undefined?b.expiresInSeconds:b.expiresIn,ttl=suppliedTtl===undefined?Number(setting(app.db,'default_share_expires')??3600):suppliedTtl,configured=setting(app.db,'default_share_downloads'),maxDownloads=b.maxDownloads!==undefined?b.maxDownloads:configured===undefined?1:Number(configured)||null,token=newToken(),id=nanoid(),expiresAt=expiryFromTtl(ttl),createdAt=now(),codeHash=b.code?await passwordHash(b.code):null;app.db.transaction(()=>{app.db.prepare('INSERT INTO shares(id,token_hash,token_value,message_id,code_hash,expires_at,max_downloads,downloads,revoked_at,created_at) VALUES(?,?,?,?,?,?,?,0,NULL,?)').run(id,sha256(token),token,messageIds[0],codeHash,expiresAt,maxDownloads,createdAt);const insert=app.db.prepare('INSERT INTO share_messages(share_id,message_id,position) VALUES(?,?,?)');messageIds.forEach((messageId,index)=>insert.run(id,messageId,index));})();return reply.code(201).send({id,token,expiresAt,maxDownloads,downloads:0,messageIds,itemCount:messageIds.length});});
  app.get('/api/shares',{preHandler:requireAuth(app,true)},async()=>({items:app.db.prepare(`SELECT s.id,s.token_value AS token,s.message_id AS messageId,s.expires_at AS expiresAt,s.max_downloads AS maxDownloads,s.downloads,s.revoked_at AS revokedAt,s.created_at AS createdAt,s.code_hash IS NOT NULL AS hasCode,m.file_name AS fileName,m.type,(SELECT count(*) FROM share_messages sm WHERE sm.share_id=s.id) AS itemCount FROM shares s JOIN messages m ON m.id=s.message_id ORDER BY s.created_at DESC`).all()}));
  app.patch('/api/shares/:id',{preHandler:requireAuth(app,true)},async(req,reply)=>{const {id}=z.object({id:z.string()}).parse(req.params),b=z.object({expiresIn:shareExpiry.optional(),maxDownloads:shareDownloadLimit.optional()}).refine(value=>value.expiresIn!==undefined||value.maxDownloads!==undefined).parse(req.body),found=app.db.prepare('SELECT id FROM shares WHERE id=? AND revoked_at IS NULL').get(id);if(!found)return reply.code(404).send({error:'not_found'});if(b.expiresIn!==undefined)app.db.prepare('UPDATE shares SET expires_at=? WHERE id=?').run(expiryFromTtl(b.expiresIn),id);if(b.maxDownloads!==undefined)app.db.prepare('UPDATE shares SET max_downloads=? WHERE id=?').run(b.maxDownloads,id);return app.db.prepare(`SELECT id,token_value AS token,message_id AS messageId,expires_at AS expiresAt,max_downloads AS maxDownloads,downloads,revoked_at AS revokedAt,created_at AS createdAt,code_hash IS NOT NULL AS hasCode FROM shares WHERE id=?`).get(id);});
  app.post('/api/shares/:id/link',{preHandler:requireAuth(app,true)},async(req,reply)=>{const {id}=z.object({id:z.string()}).parse(req.params),share=app.db.prepare('SELECT token_value AS token FROM shares WHERE id=? AND revoked_at IS NULL').get(id) as {token?:string}|undefined;if(!share)return reply.code(404).send({error:'not_found'});if(share.token)return {token:share.token,regenerated:false};const token=newToken();app.db.prepare('UPDATE shares SET token_hash=?,token_value=? WHERE id=?').run(sha256(token),token,id);return {token,regenerated:true};});
  app.delete('/api/shares/:id',{preHandler:requireAuth(app,true)},async(req)=>{const {id}=z.object({id:z.string()}).parse(req.params);app.db.prepare('UPDATE shares SET revoked_at=? WHERE id=?').run(now(),id);return {ok:true};});
  app.post('/api/public/shares/:token',async(req,reply)=>{const {token}=z.object({token:z.string()}).parse(req.params);const {code}=z.object({code:z.string().optional()}).parse(req.body??{});const s=app.db.prepare(`SELECT id,code_hash AS codeHash FROM shares WHERE token_hash=? AND revoked_at IS NULL AND ${activeExpiry} AND (max_downloads IS NULL OR downloads<max_downloads)`).get(sha256(token),now()) as {id:string;codeHash?:string}|undefined;if(!s)return reply.code(404).send({error:'not_found'});if(s.codeHash&&!code)return reply.code(401).send({error:'code_required'});if(s.codeHash&&!await passwordVerify(s.codeHash,code!))return reply.code(401).send({error:'invalid_code'});const message=messagesForShare(app,s.id)[0];return message??reply.code(404).send({error:'not_found'});});
  app.get('/api/public/shares/:token',async(req,reply)=>{const {token}=z.object({token:z.string()}).parse(req.params);const {code}=z.object({code:z.string().optional()}).parse(req.query);const s=app.db.prepare(`SELECT id,code_hash AS codeHash,expires_at AS expiresAt,max_downloads AS maxDownloads,downloads FROM shares WHERE token_hash=? AND revoked_at IS NULL AND ${activeExpiry} AND (max_downloads IS NULL OR downloads<max_downloads)`).get(sha256(token),now()) as {id:string;codeHash?:string;expiresAt:number;maxDownloads:number|null;downloads:number}|undefined;if(!s)return reply.code(404).send({error:'not_found'});if(s.codeHash&&!await passwordVerify(s.codeHash,code??''))return reply.code(401).send({error:code?'invalid_code':'code_required'});const messages=messagesForShare(app,s.id);return messages.length?{share:{expiresAt:s.expiresAt,maxDownloads:s.maxDownloads,downloads:s.downloads,itemCount:messages.length},message:messages[0],messages}:reply.code(404).send({error:'not_found'});});
  app.get('/api/public/shares/:token/items/:messageId/preview',async(req,reply)=>{const {token,messageId}=z.object({token:z.string(),messageId:z.string()}).parse(req.params),{code}=z.object({code:z.string().optional()}).parse(req.query),found=await sharedFile(app,token,code,messageId);if('error'in found)return reply.code(found.error==='not_found'?404:401).send({error:found.error});return streamInlinePreview(reply,typeof req.headers.range==='string'?req.headers.range:undefined,found.file);});
  app.get('/api/public/shares/:token/items/:messageId/download',async(req,reply)=>{const {token,messageId}=z.object({token:z.string(),messageId:z.string()}).parse(req.params),{code}=z.object({code:z.string().optional()}).parse(req.query),reserved=await reserveShareDownload(app,token,code,messageId);if('error'in reserved)return reply.code(reserved.error==='not_found'?404:401).send({error:reserved.error});const m=app.db.prepare('SELECT m.file_name,b.path,b.size FROM messages m JOIN blobs b ON b.id=m.blob_id WHERE m.id=? AND m.deleted_at IS NULL').get(reserved.messageId) as {file_name:string;path:string;size:number}|undefined;if(!m)return reply.code(404).send({error:'not_found'});markMessageDownloaded(app,reserved.messageId);return reply.header('Content-Type','application/octet-stream').header('Content-Length',m.size).header('Content-Disposition',attachmentDisposition(m.file_name)).header('Cache-Control','private, no-store').send(createReadStream(m.path));});
  app.get('/api/public/shares/:token/preview',async(req,reply)=>{const {token}=z.object({token:z.string()}).parse(req.params);const {code}=z.object({code:z.string().optional()}).parse(req.query);const found=await sharedFile(app,token,code);if('error'in found)return reply.code(found.error==='not_found'?404:401).send({error:found.error});return streamInlinePreview(reply,typeof req.headers.range==='string'?req.headers.range:undefined,found.file);});
  app.get('/api/public/shares/:token/download',async(req,reply)=>{const {token}=z.object({token:z.string()}).parse(req.params);const q=z.object({code:z.string().optional()}).parse(req.query);const reserved=await reserveShareDownload(app,token,q.code);if('error'in reserved)return reply.code(reserved.error==='not_found'?404:401).send({error:reserved.error});const m=app.db.prepare('SELECT m.file_name,b.path,b.size FROM messages m JOIN blobs b ON b.id=m.blob_id WHERE m.id=? AND m.deleted_at IS NULL').get(reserved.messageId) as {file_name:string;path:string;size:number}|undefined;if(!m)return reply.code(404).send({error:'not_found'});markMessageDownloaded(app,reserved.messageId);return reply.header('Content-Type','application/octet-stream').header('Content-Length',m.size).header('Content-Disposition',attachmentDisposition(m.file_name)).header('Cache-Control','private, no-store').send(createReadStream(m.path));});
  app.post('/api/drops',{preHandler:requireAuth(app,true)},async(req,reply)=>{const b=z.object({name:z.string().trim().min(1).max(80),expiresInSeconds:dropExpiry.optional(),expiresIn:dropExpiry.optional(),maxUploads:dropUploadLimit.default(null),maxFileSize:dropFileLimit.default(null),allowedTypes:dropTypes.default([])}).parse(req.body),ttl=b.expiresInSeconds??b.expiresIn??86400,token=newToken(),id=nanoid(),createdAt=now(),expiresAt=createdAt+ttl*1000;app.db.prepare('INSERT INTO drops(id,token_hash,token_value,name,expires_at,max_uploads,uploads,max_file_size,allowed_types,revoked_at,created_at) VALUES(?,?,?,?,?,?,0,?,?,NULL,?)').run(id,sha256(token),token,b.name,expiresAt,b.maxUploads,b.maxFileSize,JSON.stringify(b.allowedTypes),createdAt);return reply.code(201).send(managedDrop(app,id));});
  app.get('/api/drops',{preHandler:requireAuth(app,true)},async()=>({items:(app.db.prepare(`SELECT ${managedDropFields} FROM drops ORDER BY created_at DESC`).all() as {allowedTypes:string}[]).map(normalizeDrop)}));
  app.patch('/api/drops/:id',{preHandler:requireAuth(app,true)},async(req,reply)=>{const {id}=z.object({id:z.string()}).parse(req.params),b=z.object({name:z.string().trim().min(1).max(80).optional(),expiresIn:dropExpiry.optional(),maxUploads:dropUploadLimit.optional(),maxFileSize:dropFileLimit.optional(),allowedTypes:dropTypes.optional()}).refine(value=>Object.values(value).some(value=>value!==undefined)).parse(req.body),found=app.db.prepare('SELECT id FROM drops WHERE id=? AND revoked_at IS NULL').get(id);if(!found)return reply.code(404).send({error:'not_found'});const updates:string[]=[],values:unknown[]=[];if(b.name!==undefined){updates.push('name=?');values.push(b.name);}if(b.expiresIn!==undefined){updates.push('expires_at=?');values.push(now()+b.expiresIn*1000);}if(b.maxUploads!==undefined){updates.push('max_uploads=?');values.push(b.maxUploads);}if(b.maxFileSize!==undefined){updates.push('max_file_size=?');values.push(b.maxFileSize);}if(b.allowedTypes!==undefined){updates.push('allowed_types=?');values.push(JSON.stringify(b.allowedTypes));}app.db.prepare(`UPDATE drops SET ${updates.join(',')} WHERE id=?`).run(...values,id);return managedDrop(app,id);});
  app.post('/api/drops/:id/link',{preHandler:requireAuth(app,true)},async(req,reply)=>{const {id}=z.object({id:z.string()}).parse(req.params),drop=app.db.prepare('SELECT token_value AS token FROM drops WHERE id=? AND revoked_at IS NULL').get(id) as {token?:string}|undefined;if(!drop)return reply.code(404).send({error:'not_found'});if(drop.token)return {token:drop.token,regenerated:false};const token=newToken();app.db.prepare('UPDATE drops SET token_hash=?,token_value=? WHERE id=?').run(sha256(token),token,id);return {token,regenerated:true};});
  app.delete('/api/drops/:id',{preHandler:requireAuth(app,true)},async req=>{const {id}=z.object({id:z.string()}).parse(req.params);app.db.prepare('UPDATE drops SET revoked_at=? WHERE id=?').run(now(),id);return {ok:true};});
  app.get('/api/public/drops/:token',async(req,reply)=>{const {token}=z.object({token:z.string()}).parse(req.params),drop=app.db.prepare('SELECT name,expires_at AS expiresAt,max_file_size AS maxFileSize,allowed_types AS allowedTypes FROM drops WHERE token_hash=? AND revoked_at IS NULL AND expires_at>? AND (max_uploads IS NULL OR uploads<max_uploads)').get(sha256(token),now()) as {allowedTypes:string}|undefined;return drop?{drop:normalizeDrop(drop)}:reply.code(404).send({error:'not_found'});});
  const receiveDrop=async(req:any,reply:any)=>{const {token}=z.object({token:z.string()}).parse(req.params);const d=reserveDrop(app,token);if(!d)return reply.code(404).send({error:'not_found'});try{const item=await saveUpload(app,req,false,d.id);app.broadcast({type:'message.created',message:item});return reply.code(201).send({ok:true,messageId:item.id});}catch(error){app.db.prepare('UPDATE drops SET uploads=MAX(uploads-1,0) WHERE id=?').run(d.id);throw error;}};
  app.post('/api/public/drops/:token/upload',receiveDrop);
  app.post('/api/public/drops/:token',receiveDrop);
}
