<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { Archive, Check, ChevronRight, Database, HardDrive, KeyRound, Laptop, Moon, RefreshCcw, SearchCheck, ShieldAlert, Sun, Trash2, X } from 'lucide-vue-next'
import { useRouter } from 'vue-router'
import { api, errorText } from '../api'
import { clearSession, state } from '../state'
import type { Device, Settings } from '../types'
import { formatBytes, formatTime, notify } from '../ui'
import BaseDialog from '../components/BaseDialog.vue'

const router=useRouter(); const loading=ref(true); const error=ref(''); const settings=ref<Settings>({ocrEnabled:true}); const devices=ref<Device[]>([]); const passwordOpen=ref(false); const dangerOpen=ref(false); const currentAdmin=ref(''); const newMain=ref(''); const newAdmin=ref(''); const confirmPassword=ref(''); const revokeDevices=ref(false); const saving=ref(false); const theme=ref(localStorage.getItem('theme') ?? 'system')
const ocr = computed(()=>settings.value.ocr ?? {completed:0,pending:0,processing:0,failed:0}); const storagePercent=computed(()=>settings.value.storage?.limit ? Math.min(100,((settings.value.storage.used??0)/settings.value.storage.limit)*100):0)
async function load(){try{const [s,d]=await Promise.all([api.settings(),api.devices()]);settings.value=s;state.settings=s;devices.value=d.items}catch(e){error.value=errorText(e)}finally{loading.value=false}}
async function save(patch:Partial<Settings>){try{settings.value=await api.updateSettings(patch);state.settings=settings.value;notify('设置已保存','success')}catch(e){notify(errorText(e),'error')}}
async function reindex(scope:'failed'|'all'){if(scope==='all'&&!confirm('重新识别全部图片会在后台排队执行，继续？'))return;try{const r=await api.rerunOcr(scope);notify(`已加入 ${r.queued??0} 个识别任务`,'success');load()}catch(e){notify(errorText(e),'error')}}
async function changePasswords(){if(newMain.value&&newMain.value!==confirmPassword.value){notify('新主口令两次输入不一致','error');return}saving.value=true;try{await api.updatePasswords({adminPassword:currentAdmin.value,newMainPassword:newMain.value||undefined,newAdminPassword:newAdmin.value||undefined,revokeDevices:revokeDevices.value});passwordOpen.value=false;notify('口令已修改','success');if(newAdmin.value||revokeDevices.value){clearSession();router.replace('/login')}}catch(e){notify(errorText(e),'error')}finally{saving.value=false}}
async function revoke(device:Device){if(!confirm(`撤销“${device.name}”的长期权限？`))return;try{await api.revokeDevice(device.id);devices.value=devices.value.filter(d=>d.id!==device.id);if(device.current){clearSession();router.replace('/login')}}catch(e){notify(errorText(e),'error')}}
async function emptyTrash(){try{await api.emptyTrash(currentAdmin.value);dangerOpen.value=false;currentAdmin.value='';notify('回收站已清空','success')}catch(e){notify(errorText(e),'error')}}
function setTheme(value:string){theme.value=value;localStorage.setItem('theme',value);document.documentElement.dataset.theme=value==='system'?'':value}
onMounted(load)
</script>
<template><section class="page settings-page"><header class="page-head"><div><p class="eyebrow">仅长期设备</p><h1>设置</h1></div></header><div v-if="loading" class="skeleton-list"><i v-for="n in 5" :key="n" /></div><div v-else-if="error" class="error-panel"><ShieldAlert :size="28" /><h2>设置读取失败</h2><p>{{error}}</p><button class="secondary-button" @click="load">重试</button></div><div v-else class="settings-stack">
  <section class="settings-card"><header><div><SearchCheck :size="20"/><span><h2>OCR 图片搜索</h2><p>上传后异步识别，搜索时直接查索引</p></span></div><input :checked="settings.ocrEnabled" type="checkbox" role="switch" @change="save({ocrEnabled:($event.target as HTMLInputElement).checked})" /></header><div class="stat-grid"><div><strong>{{ocr.completed}}</strong><span>已完成</span></div><div><strong>{{ocr.pending}}</strong><span>排队中</span></div><div><strong>{{ocr.processing}}</strong><span>识别中</span></div><div><strong>{{ocr.failed}}</strong><span>失败</span></div></div><div class="button-row"><button class="secondary-button" :disabled="!ocr.failed" @click="reindex('failed')"><RefreshCcw :size="16"/>重试失败图片</button><button class="secondary-button" @click="reindex('all')"><RefreshCcw :size="16"/>重新识别全部</button></div></section>
  <section class="settings-card"><header><div><HardDrive :size="20"/><span><h2>存储与自动清理</h2><p>收藏和置顶内容默认不自动清理</p></span></div></header><div class="storage-line"><strong>{{formatBytes(settings.storage?.used)}}</strong><span v-if="settings.storage?.limit">/ {{formatBytes(settings.storage.limit)}}</span></div><div class="progress storage"><i :style="{width:`${storagePercent}%`} "/></div><div class="two-col"><label class="field"><span>图片保留天数</span><input :value="settings.retention?.imagesDays" type="number" min="1" @change="save({retention:{...settings.retention,imagesDays:Number(($event.target as HTMLInputElement).value)}})" /></label><label class="field"><span>文件保留天数</span><input :value="settings.retention?.filesDays" type="number" min="1" @change="save({retention:{...settings.retention,filesDays:Number(($event.target as HTMLInputElement).value)}})" /></label><label class="field"><span>回收站保留天数</span><input :value="settings.retention?.trashDays" type="number" min="1" @change="save({retention:{...settings.retention,trashDays:Number(($event.target as HTMLInputElement).value)}})" /></label><label class="field"><span>存储上限（GB，0 为不限）</span><input :value="settings.storage?.limit ? Math.round(settings.storage.limit/1073741824*100)/100 : 0" type="number" min="0" step="0.1" @change="save({storage:{limit:Number(($event.target as HTMLInputElement).value)>0?Math.round(Number(($event.target as HTMLInputElement).value)*1073741824):null}})" /></label></div><label class="check-row"><input :checked="settings.retention?.downloadedEarlier" type="checkbox" @change="save({retention:{...settings.retention,downloadedEarlier:($event.target as HTMLInputElement).checked}})"/><span>已下载文件优先进入回收站</span></label></section>
  <section class="settings-card"><header><div><Database :size="20"/><span><h2>临时分享默认值</h2><p>创建分享时仍可单独调整</p></span></div></header><div class="two-col"><label class="field"><span>有效期（分钟）</span><input :value="Math.round((settings.defaultShare?.expiresIn??3600)/60)" type="number" min="1" max="43200" @change="save({defaultShare:{expiresIn:Number(($event.target as HTMLInputElement).value)*60,maxDownloads:settings.defaultShare?.maxDownloads}})" /></label><label class="field"><span>最大下载次数（0 为不限）</span><input :value="settings.defaultShare?.maxDownloads??0" type="number" min="0" @change="save({defaultShare:{expiresIn:settings.defaultShare?.expiresIn??3600,maxDownloads:Number(($event.target as HTMLInputElement).value)||null}})" /></label></div></section>
  <section class="settings-card"><header><div><Laptop :size="20"/><span><h2>长期设备</h2><p>可单独撤销任何已授权设备</p></span></div></header><div class="device-list"><article v-for="device in devices" :key="device.id"><div class="device-dot" :class="{online:device.online}"/><div><strong>{{device.name}} <small v-if="device.current">当前</small></strong><span>{{formatTime(device.lastSeenAt)}} 活跃<template v-if="device.lastIp"> · {{device.lastIp}}</template></span></div><button class="icon-button danger-text" aria-label="撤销设备" @click="revoke(device)"><X :size="18"/></button></article></div></section>
  <section class="settings-card compact-card"><button class="settings-row" @click="passwordOpen=true"><span><KeyRound :size="19"/><span><strong>修改口令</strong><small>主口令与管理口令</small></span></span><ChevronRight :size="18"/></button><a class="settings-row" :href="api.exportBackup()"><span><Archive :size="19"/><span><strong>导出数据库快照</strong><small>仅含消息与设置；完整恢复还需服务器文件备份</small></span></span><ChevronRight :size="18"/></a></section>
  <section class="settings-card"><header><div><Moon :size="20"/><span><h2>外观</h2><p>跟随系统或指定浅色、深色主题</p></span></div></header><div class="segmented"><button :class="{active:theme==='system'}" @click="setTheme('system')"><Laptop :size="15"/>系统</button><button :class="{active:theme==='light'}" @click="setTheme('light')"><Sun :size="15"/>浅色</button><button :class="{active:theme==='dark'}" @click="setTheme('dark')"><Moon :size="15"/>深色</button></div></section>
  <section class="settings-card danger-zone"><header><div><ShieldAlert :size="20"/><span><h2>危险操作</h2><p>执行前需要重新输入管理口令</p></span></div></header><button class="danger-button" @click="dangerOpen=true"><Trash2 :size="17"/>清空回收站</button></section>
 </div>
 <BaseDialog :open="passwordOpen" title="修改口令" @close="passwordOpen=false"><form class="stack" @submit.prevent="changePasswords"><label class="field"><span>当前管理口令</span><input v-model="currentAdmin" type="password" required /></label><label class="field"><span>新主口令（留空不修改）</span><input v-model="newMain" type="password" minlength="8" /></label><label v-if="newMain" class="field"><span>再次输入新主口令</span><input v-model="confirmPassword" type="password" minlength="8" /></label><label class="field"><span>新管理口令（留空不修改）</span><input v-model="newAdmin" type="password" minlength="8" /></label><label class="check-row"><input v-model="revokeDevices" type="checkbox"/><span>同时退出全部长期设备</span></label><div v-if="newAdmin" class="warning-callout"><ShieldAlert :size="18"/>修改管理口令后，所有长期设备将被撤销。</div><button class="primary-button" :disabled="saving">确认修改</button></form></BaseDialog>
 <BaseDialog :open="dangerOpen" title="清空回收站" @close="dangerOpen=false"><form class="stack" @submit.prevent="emptyTrash"><div class="warning-callout"><Trash2 :size="18"/>这些内容将无法恢复，且会释放已无其他引用的文件。</div><label class="field"><span>输入管理口令确认</span><input v-model="currentAdmin" type="password" required /></label><button class="danger-button">永久清空</button></form></BaseDialog>
</section></template>
