<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { Archive, Check, ChevronRight, Database, HardDrive, KeyRound, Laptop, Moon, RefreshCcw, SearchCheck, ShieldAlert, Sun, Trash2, X } from 'lucide-vue-next'
import { useRouter } from 'vue-router'
import { api, errorText } from '../api'
import { clearSession, state } from '../state'
import type { Device, OcrJobItem, OcrJobStatus, Settings } from '../types'
import { formatBytes, formatTime, notify, requestConfirm } from '../ui'
import BaseDialog from '../components/BaseDialog.vue'
import MessageCard from '../components/MessageCard.vue'

const router=useRouter(); const loading=ref(true); const error=ref(''); const settings=ref<Settings>({ocrEnabled:true}); const devices=ref<Device[]>([]); const passwordOpen=ref(false); const dangerOpen=ref(false); const currentAdmin=ref(''); const newMain=ref(''); const newAdmin=ref(''); const confirmPassword=ref(''); const revokeDevices=ref(false); const saving=ref(false); const theme=ref(localStorage.getItem('theme') ?? 'system')
let settingsSaveQueue=Promise.resolve()
const storageDraft=ref({imagesDays:-1,filesDays:-1,trashDays:-1,downloadedEarlier:false,limitGb:0}); const storageSaving=ref(false)
const ocrJobsOpen=ref(false); const ocrJobStatus=ref<OcrJobStatus>('done'); const ocrItems=ref<OcrJobItem[]>([]); const ocrItemsLoading=ref(false); const ocrItemsMoreLoading=ref(false); const ocrItemsError=ref(''); const ocrItemsTotal=ref(0); const ocrNextOffset=ref<number|null>(null)
const ocr = computed(()=>settings.value.ocr ?? {completed:0,pending:0,processing:0,failed:0}); const storagePercent=computed(()=>settings.value.storage?.limit ? Math.min(100,((settings.value.storage.used??0)/settings.value.storage.limit)*100):0)
const ocrLabels:Record<OcrJobStatus,string>={done:'已完成',pending:'排队中',processing:'识别中',failed:'识别失败'}; const ocrJobsTitle=computed(()=>`${ocrLabels[ocrJobStatus.value]}的图片`)
function syncStorageDraft(){storageDraft.value={imagesDays:settings.value.retention?.imagesDays??-1,filesDays:settings.value.retention?.filesDays??-1,trashDays:settings.value.retention?.trashDays??-1,downloadedEarlier:Boolean(settings.value.retention?.downloadedEarlier),limitGb:settings.value.storage?.limit?Math.round(settings.value.storage.limit/1073741824*100)/100:0}}
async function load(){try{const [s,d]=await Promise.all([api.settings(),api.devices()]);settings.value=s;state.settings=s;devices.value=d.items;syncStorageDraft()}catch(e){error.value=errorText(e)}finally{loading.value=false}}
async function loadOcrJobs(more=false){if(more)ocrItemsMoreLoading.value=true;else{ocrItemsLoading.value=true;ocrItemsError.value=''}try{const result=await api.ocrJobs(ocrJobStatus.value,more?(ocrNextOffset.value??0):0);ocrItems.value=more?[...ocrItems.value,...result.items]:result.items;ocrItemsTotal.value=result.total;ocrNextOffset.value=result.nextOffset}catch(e){ocrItemsError.value=errorText(e)}finally{ocrItemsLoading.value=false;ocrItemsMoreLoading.value=false}}
function openOcrJobs(status:OcrJobStatus){ocrJobStatus.value=status;ocrItems.value=[];ocrItemsTotal.value=0;ocrNextOffset.value=null;ocrJobsOpen.value=true;void loadOcrJobs()}
function save(patch:Partial<Settings>){let succeeded=false;settingsSaveQueue=settingsSaveQueue.then(async()=>{try{settings.value=await api.updateSettings(patch);state.settings=settings.value;succeeded=true;notify('设置已保存','success')}catch(e){notify(errorText(e),'error')}});return settingsSaveQueue.then(()=>succeeded)}
async function saveStorage(){const draft=storageDraft.value,days=[draft.imagesDays,draft.filesDays,draft.trashDays];if(days.some(value=>value===0||!Number.isInteger(value)||value< -1)){notify('保留天数请填写 -1 或大于 0 的整数','error');return}if(!Number.isFinite(draft.limitGb)||draft.limitGb<0){notify('存储上限不能小于 0','error');return}storageSaving.value=true;try{const succeeded=await save({retention:{imagesDays:draft.imagesDays,filesDays:draft.filesDays,trashDays:draft.trashDays,downloadedEarlier:draft.downloadedEarlier},storage:{limit:draft.limitGb>0?Math.round(draft.limitGb*1073741824):null}});if(succeeded)syncStorageDraft()}finally{storageSaving.value=false}}
async function reindex(scope:'failed'|'all'){if(scope==='all'&&!await requestConfirm('全部图片会重新加入后台识别队列。',{title:'重新识别全部图片',confirmText:'开始识别'}))return;try{const r=await api.rerunOcr(scope);notify(`已加入 ${r.queued??0} 个识别任务`,'success');load()}catch(e){notify(errorText(e),'error')}}
async function changePasswords(){if(newMain.value&&newMain.value!==confirmPassword.value){notify('新主口令两次输入不一致','error');return}saving.value=true;try{await api.updatePasswords({adminPassword:currentAdmin.value,newMainPassword:newMain.value||undefined,newAdminPassword:newAdmin.value||undefined,revokeDevices:revokeDevices.value});passwordOpen.value=false;notify('口令已修改','success');if(newAdmin.value||revokeDevices.value){clearSession();router.replace('/login')}}catch(e){notify(errorText(e),'error')}finally{saving.value=false}}
async function revoke(device:Device){if(!await requestConfirm(`撤销“${device.name}”的长期权限？撤销后该设备需要重新登录。`,{title:'撤销长期设备',confirmText:'确认撤销',danger:true}))return;try{await api.revokeDevice(device.id);devices.value=devices.value.filter(d=>d.id!==device.id);if(device.current){clearSession();router.replace('/login')}}catch(e){notify(errorText(e),'error')}}
async function emptyTrash(){try{await api.emptyTrash(currentAdmin.value);dangerOpen.value=false;currentAdmin.value='';notify('回收站已清空','success')}catch(e){notify(errorText(e),'error')}}
function setTheme(value:string){theme.value=value;localStorage.setItem('theme',value);document.documentElement.dataset.theme=value==='system'?'':value}
onMounted(load)
</script>
<template><section class="page settings-page"><header class="page-head"><div><p class="eyebrow">仅长期设备</p><h1>设置</h1></div></header><div v-if="loading" class="skeleton-list"><i v-for="n in 5" :key="n" /></div><div v-else-if="error" class="error-panel"><ShieldAlert :size="28" /><h2>设置读取失败</h2><p>{{error}}</p><button class="secondary-button" @click="load">重试</button></div><div v-else class="settings-stack">
  <section class="settings-card"><header><div><SearchCheck :size="20"/><span><h2>OCR 图片搜索</h2><p>上传后异步识别，点击状态可查看对应图片</p></span></div><input :checked="settings.ocrEnabled" type="checkbox" role="switch" @change="save({ocrEnabled:($event.target as HTMLInputElement).checked})" /></header><div class="stat-grid"><button type="button" aria-label="查看已完成的图片" @click="openOcrJobs('done')"><strong>{{ocr.completed}}</strong><span>已完成 <ChevronRight :size="11"/></span></button><button type="button" aria-label="查看排队中的图片" @click="openOcrJobs('pending')"><strong>{{ocr.pending}}</strong><span>排队中 <ChevronRight :size="11"/></span></button><button type="button" aria-label="查看识别中的图片" @click="openOcrJobs('processing')"><strong>{{ocr.processing}}</strong><span>识别中 <ChevronRight :size="11"/></span></button><button type="button" aria-label="查看识别失败的图片" @click="openOcrJobs('failed')"><strong>{{ocr.failed}}</strong><span>失败 <ChevronRight :size="11"/></span></button></div><div class="button-row"><button class="secondary-button" :disabled="!ocr.failed" @click="reindex('failed')"><RefreshCcw :size="16"/>重试失败图片</button><button class="secondary-button" @click="reindex('all')"><RefreshCcw :size="16"/>重新识别全部</button></div></section>
  <section class="settings-card"><header><div><HardDrive :size="20"/><span><h2>存储与自动清理</h2><p>默认永久保留；修改完成后统一保存</p></span></div></header><div class="storage-line"><strong>{{formatBytes(settings.storage?.used)}}</strong><span v-if="settings.storage?.limit">/ {{formatBytes(settings.storage.limit)}}</span></div><div class="progress storage"><i :style="{width:`${storagePercent}%`} "/></div><div class="two-col"><label class="field"><span>图片保留天数（-1 为永久）</span><input v-model.number="storageDraft.imagesDays" type="number" min="-1" /></label><label class="field"><span>文件保留天数（-1 为永久）</span><input v-model.number="storageDraft.filesDays" type="number" min="-1" /></label><label class="field"><span>回收站保留天数（-1 为永久）</span><input v-model.number="storageDraft.trashDays" type="number" min="-1" /></label><label class="field"><span>存储上限（GB，0 为不限）</span><input v-model.number="storageDraft.limitGb" type="number" min="0" step="0.1" /></label></div><label class="check-row"><input v-model="storageDraft.downloadedEarlier" type="checkbox"/><span>已下载文件优先进入回收站</span></label><button class="primary-button full" :disabled="storageSaving" @click="saveStorage"><Check :size="17"/>{{storageSaving?'保存中…':'保存存储设置'}}</button></section>
  <section class="settings-card"><header><div><Database :size="20"/><span><h2>临时分享默认值</h2><p>创建分享时仍可单独调整</p></span></div></header><div class="two-col"><label class="field"><span>有效期（分钟）</span><input :value="Math.round((settings.defaultShare?.expiresIn??3600)/60)" type="number" min="1" max="43200" @change="save({defaultShare:{expiresIn:Number(($event.target as HTMLInputElement).value)*60,maxDownloads:settings.defaultShare?.maxDownloads}})" /></label><label class="field"><span>最大下载次数（0 为不限）</span><input :value="settings.defaultShare?.maxDownloads??0" type="number" min="0" @change="save({defaultShare:{expiresIn:settings.defaultShare?.expiresIn??3600,maxDownloads:Number(($event.target as HTMLInputElement).value)||null}})" /></label></div></section>
  <section class="settings-card"><header><div><Laptop :size="20"/><span><h2>长期设备</h2><p>可单独撤销任何已授权设备</p></span></div></header><div class="device-list"><article v-for="device in devices" :key="device.id"><div class="device-dot" :class="{online:device.online}"/><div><strong>{{device.name}} <small v-if="device.current">当前</small></strong><span>{{formatTime(device.lastSeenAt)}} 活跃<template v-if="device.lastIp"> · {{device.lastIp}}</template></span></div><button class="icon-button danger-text" aria-label="撤销设备" @click="revoke(device)"><X :size="18"/></button></article></div></section>
  <section class="settings-card compact-card"><button class="settings-row" @click="passwordOpen=true"><span><KeyRound :size="19"/><span><strong>修改口令</strong><small>主口令与管理口令</small></span></span><ChevronRight :size="18"/></button><a class="settings-row" :href="api.exportBackup()"><span><Archive :size="19"/><span><strong>导出数据库快照</strong><small>仅含消息与设置；完整恢复还需服务器文件备份</small></span></span><ChevronRight :size="18"/></a></section>
  <section class="settings-card"><header><div><Moon :size="20"/><span><h2>外观</h2><p>跟随系统或指定浅色、深色主题</p></span></div></header><div class="segmented"><button :class="{active:theme==='system'}" @click="setTheme('system')"><Laptop :size="15"/>系统</button><button :class="{active:theme==='light'}" @click="setTheme('light')"><Sun :size="15"/>浅色</button><button :class="{active:theme==='dark'}" @click="setTheme('dark')"><Moon :size="15"/>深色</button></div></section>
  <section class="settings-card danger-zone"><header><div><ShieldAlert :size="20"/><span><h2>危险操作</h2><p>执行前需要重新输入管理口令</p></span></div></header><button class="danger-button" @click="dangerOpen=true"><Trash2 :size="17"/>清空回收站</button></section>
 </div>
 <BaseDialog :open="passwordOpen" title="修改口令" @close="passwordOpen=false"><form class="stack" @submit.prevent="changePasswords"><label class="field"><span>当前管理口令</span><input v-model="currentAdmin" type="password" required /></label><label class="field"><span>新主口令（留空不修改）</span><input v-model="newMain" type="password" minlength="8" /></label><label v-if="newMain" class="field"><span>再次输入新主口令</span><input v-model="confirmPassword" type="password" minlength="8" /></label><label class="field"><span>新管理口令（留空不修改）</span><input v-model="newAdmin" type="password" minlength="8" /></label><label class="check-row"><input v-model="revokeDevices" type="checkbox"/><span>同时退出全部长期设备</span></label><div v-if="newAdmin" class="warning-callout"><ShieldAlert :size="18"/>修改管理口令后，所有长期设备将被撤销。</div><button class="primary-button" :disabled="saving">确认修改</button></form></BaseDialog>
 <BaseDialog :open="dangerOpen" title="清空回收站" @close="dangerOpen=false"><form class="stack" @submit.prevent="emptyTrash"><div class="warning-callout"><Trash2 :size="18"/>这些内容将无法恢复，且会释放已无其他引用的文件。</div><label class="field"><span>输入管理口令确认</span><input v-model="currentAdmin" type="password" required /></label><button class="danger-button">永久清空</button></form></BaseDialog>
 <BaseDialog :open="ocrJobsOpen" :title="ocrJobsTitle" wide @close="ocrJobsOpen=false"><div class="ocr-job-summary"><span>共 {{ocrItemsTotal}} 张</span><button class="text-button" :disabled="ocrItemsLoading" @click="loadOcrJobs()"><RefreshCcw :size="14"/>刷新</button></div><div v-if="ocrItemsLoading" class="skeleton-list"><i v-for="n in 3" :key="n"/></div><div v-else-if="ocrItemsError" class="error-panel compact"><ShieldAlert :size="24"/><p>{{ocrItemsError}}</p><button class="secondary-button" @click="loadOcrJobs()">重试</button></div><div v-else-if="!ocrItems.length" class="ocr-job-empty"><SearchCheck :size="28"/><strong>暂无{{ocrLabels[ocrJobStatus]}}的图片</strong><span>任务状态变化后，可点击刷新查看。</span></div><div v-else class="ocr-job-list"><div v-for="item in ocrItems" :key="item.id" class="ocr-job-item"><MessageCard :message="item" readonly/><div v-if="item.jobStatus==='done'" class="ocr-result"><strong>识别内容</strong><p v-if="item.ocrText?.trim()">{{item.ocrText}}</p><span v-else>未识别到文字</span></div><div class="ocr-job-detail"><span>{{ocrLabels[item.jobStatus]}} · {{formatTime(item.jobUpdatedAt)}}</span><span v-if="item.attempts">已尝试 {{item.attempts}} 次</span><p v-if="item.error" :title="item.error">{{item.error}}</p></div></div><button v-if="ocrNextOffset!==null" class="secondary-button full" :disabled="ocrItemsMoreLoading" @click="loadOcrJobs(true)">{{ocrItemsMoreLoading?'加载中…':'加载更多'}}</button></div></BaseDialog>
</section></template>
