<script setup lang="ts">
import { onMounted, onUnmounted, ref } from 'vue'
import { Ban, Clock3, Inbox, Link2, Pencil, Plus, QrCode, SendToBack, ShieldAlert } from 'lucide-vue-next'
import { api, errorText } from '../api'
import { isTrusted } from '../state'
import type { Drop, Share } from '../types'
import { formatBytes, formatTime, notify, requestConfirm } from '../ui'
import BaseDialog from '../components/BaseDialog.vue'
import DropParameterFields from '../components/DropParameterFields.vue'
import EmptyState from '../components/EmptyState.vue'
import LinkQrDialog from '../components/LinkQrDialog.vue'
import ShareParameterFields from '../components/ShareParameterFields.vue'
import { defaultDropValues } from '../drop-defaults'

const tab=ref<'shares'|'drops'>('shares');const shares=ref<Share[]>([]);const drops=ref<Drop[]>([]);const loading=ref(true);const error=ref('')
const dropOpen=ref(false);const editingDrop=ref<Drop>();const dropSaving=ref(false);const name=ref('给我投递文件');const expiresIn=ref<number|undefined>(86400);const maxUploads=ref<number|null>(5);const maxFileSizeMb=ref<number|null>(500);const allowedTypes=ref<string[]>([])
const linkOpen=ref(false);const linkValue=ref('');const linkTitle=ref('链接');const linkDescription=ref('')
const shareEditOpen=ref(false);const editingShare=ref<Share>();const editExpiresIn=ref<number|null|undefined>();const editMaxDownloads=ref<number|null|undefined>();const shareEditSaving=ref(false)

async function load(){loading.value=true;try{if(isTrusted.value){shares.value=(await api.shares()).items;drops.value=(await api.drops()).items}}catch(e){error.value=errorText(e)}finally{loading.value=false}}
async function revokeShare(id:string){if(!await requestConfirm('撤销后链接将立即失效。',{title:'撤销临时分享',confirmText:'确认撤销',danger:true}))return;await api.revokeShare(id);shares.value=shares.value.filter(value=>value.id!==id)}
async function revokeDrop(id:string){if(!await requestConfirm('关闭后将无法继续通过此链接投递。',{title:'关闭投递箱',confirmText:'确认关闭',danger:true}))return;await api.revokeDrop(id);drops.value=drops.value.filter(value=>value.id!==id)}
function resetDropForm(){const defaults=defaultDropValues();editingDrop.value=undefined;name.value=defaults.name;expiresIn.value=defaults.expiresIn;maxUploads.value=defaults.maxUploads;maxFileSizeMb.value=defaults.maxFileSize/1024/1024;allowedTypes.value=[...defaults.allowedTypes]}
function openDropCreator(){resetDropForm();dropOpen.value=true}
function openDropEditor(item:Drop){editingDrop.value=item;name.value=item.name;expiresIn.value=undefined;maxUploads.value=item.maxUploads??null;maxFileSizeMb.value=item.maxFileSize?Math.round(item.maxFileSize/1024/1024):null;allowedTypes.value=[...(item.allowedTypes??[])];dropOpen.value=true}
async function showDropLink(item:Drop){try{if(!item.token){const result=await api.revealDropLink(item.id);item.token=result.token;if(result.regenerated)notify('旧版本未保存原链接，已生成新的投递链接，原链接将失效','success')}linkTitle.value=item.name;linkValue.value=dropLink(item);linkDescription.value='把链接或二维码发给对方，对方只能向你投递，无法查看已有内容。';linkOpen.value=true}catch(e){notify(errorText(e),'error')}}
async function showShareLink(item:Share){try{if(!item.url&&!item.token){const result=await api.revealShareLink(item.id);item.token=result.token;if(result.regenerated)notify('旧版本未保存原链接，已生成新的分享链接，原链接将失效','success')}linkTitle.value=(item.itemCount??1)>1?'组合分享链接':(item.fileName||'临时分享链接');linkValue.value=shareLink(item);linkDescription.value='链接有效期和下载次数以当前分享参数为准。';linkOpen.value=true}catch(e){notify(errorText(e),'error')}}
async function saveDrop(){if(!name.value.trim()){notify('请输入投递箱标题','error');return}dropSaving.value=true;try{const values={name:name.value.trim(),maxUploads:maxUploads.value,maxFileSize:maxFileSizeMb.value===null?null:Math.round(maxFileSizeMb.value*1024*1024),allowedTypes:allowedTypes.value,...(expiresIn.value!==undefined?{expiresIn:expiresIn.value}:{})};if(editingDrop.value){const updated=await api.updateDrop(editingDrop.value.id,values);Object.assign(editingDrop.value,updated);dropOpen.value=false;notify('投递参数已更新','success')}else{const created=await api.createDrop({...values,expiresIn:expiresIn.value??86400});drops.value.unshift(created);dropOpen.value=false;notify('投递链接已创建','success');await showDropLink(created)}}catch(e){notify(errorText(e),'error')}finally{dropSaving.value=false}}
function openShareEditor(item:Share){editingShare.value=item;editExpiresIn.value=undefined;editMaxDownloads.value=undefined;shareEditOpen.value=true}
async function saveShare(){const item=editingShare.value;if(!item||editExpiresIn.value===undefined&&editMaxDownloads.value===undefined)return;shareEditSaving.value=true;try{const updated=await api.updateShare(item.id,{...(editExpiresIn.value!==undefined?{expiresIn:editExpiresIn.value}:{}),...(editMaxDownloads.value!==undefined?{maxDownloads:editMaxDownloads.value}:{})});Object.assign(item,updated);shareEditOpen.value=false;notify('分享参数已更新','success')}catch(e){notify(errorText(e),'error')}finally{shareEditSaving.value=false}}
function expiryLabel(item:Share){return item.expiresAt===0?'永久有效':`${formatTime(item.expiresAt)} 到期`}
function dropExpiryLabel(item:Drop){return `${formatTime(item.expiresAt)} 到期`}
function downloadLabel(item:Share){return `${item.downloads} / ${item.maxDownloads??'∞'} 次下载`}
function fileSizeLabel(item:Drop){return item.maxFileSize?formatBytes(item.maxFileSize):'跟随服务器上限'}
function shareLink(item:Share){return item.url??`${location.origin}/s/${item.token}`}
function dropLink(item:Drop){return item.url??`${location.origin}/drop/${item.token}`}
const refreshDrops=()=>{if(isTrusted.value)void api.drops().then(result=>{drops.value=result.items}).catch(()=>{})}
onMounted(()=>{void load();window.addEventListener('drops-changed',refreshDrops)})
onUnmounted(()=>window.removeEventListener('drops-changed',refreshDrops))
</script>

<template><section class="page"><header class="page-head"><div><p class="eyebrow">对外传递</p><h1>传输管理</h1></div><button v-if="tab==='drops'&&isTrusted" class="primary-button compact" @click="openDropCreator"><Plus :size="17"/>新建</button></header>
  <div class="segmented"><button :class="{active:tab==='shares'}" @click="tab='shares'"><Link2 :size="16"/>临时分享</button><button :class="{active:tab==='drops'}" @click="tab='drops'"><SendToBack :size="16"/>外部投递</button></div>
  <div v-if="loading" class="skeleton-list"><i v-for="n in 3" :key="n"/></div><EmptyState v-else-if="error" :icon="ShieldAlert" title="传输记录读取失败" :description="error"/>
  <template v-else-if="tab==='shares'"><EmptyState v-if="!shares.length" :icon="Link2" title="暂无有效分享" description="在任意消息的操作菜单中创建临时分享。"/><div v-else class="transfer-list"><article v-for="item in shares" :key="item.id"><div class="transfer-icon"><Link2 :size="20"/></div><div><strong>{{(item.itemCount??1)>1?`${item.itemCount} 项组合分享`:(item.fileName||'单条内容分享')}}</strong><span><Clock3 :size="13"/>{{expiryLabel(item)}} · {{downloadLabel(item)}}</span><small>{{item.url||item.token?'可随时查看链接和二维码':'查看时将为旧记录生成新链接'}}</small></div><div class="transfer-actions"><button class="icon-button" aria-label="查看分享链接和二维码" @click="showShareLink(item)"><QrCode :size="17"/></button><button class="icon-button" aria-label="编辑分享参数" @click="openShareEditor(item)"><Pencil :size="17"/></button><button class="icon-button danger-text" aria-label="撤销分享" @click="revokeShare(item.id)"><Ban :size="17"/></button></div></article></div></template>
  <template v-else><div v-if="!isTrusted" class="locked-panel"><ShieldAlert :size="28"/><h2>仅长期设备可创建投递箱</h2><p>请先在“我的”中输入管理口令，将当前设备设为长期设备。</p><RouterLink class="primary-button" to="/app/profile?upgrade=1">设为长期设备</RouterLink></div><EmptyState v-else-if="!drops.length" :icon="Inbox" title="还没有投递箱" description="创建一个限时入口，让他人只能向你上传。"><button class="primary-button" @click="openDropCreator"><Plus :size="17"/>创建投递箱</button></EmptyState><div v-else class="transfer-list"><article v-for="item in drops" :key="item.id"><div class="transfer-icon"><Inbox :size="20"/></div><div><strong>{{item.name}}</strong><span><Clock3 :size="13"/>{{dropExpiryLabel(item)}} · {{item.uploads}} / {{item.maxUploads??'∞'}} 次</span><small>单文件 {{fileSizeLabel(item)}} · {{item.token?'可随时查看链接和二维码':'查看时将为旧记录生成新链接'}}</small></div><div class="transfer-actions"><button class="icon-button" aria-label="查看投递链接和二维码" @click="showDropLink(item)"><QrCode :size="17"/></button><button class="icon-button" aria-label="编辑投递参数" @click="openDropEditor(item)"><Pencil :size="17"/></button><button class="icon-button danger-text" aria-label="关闭投递箱" @click="revokeDrop(item.id)"><Ban :size="17"/></button></div></article></div></template>
  <BaseDialog :open="dropOpen" :title="editingDrop?'编辑外部投递':'创建外部投递'" @close="dropOpen=false"><form class="stack" @submit.prevent="saveDrop"><label class="field"><span>投递箱标题</span><input v-model="name" maxlength="80" placeholder="例如：给我投递文件"/></label><DropParameterFields v-model:expires-in="expiresIn" v-model:max-uploads="maxUploads" v-model:max-file-size-mb="maxFileSizeMb" v-model:allowed-types="allowedTypes" :allow-unchanged-expiry="Boolean(editingDrop)" :uploads="editingDrop?.uploads??0"/><button class="primary-button" :disabled="dropSaving">{{dropSaving?'保存中…':editingDrop?'保存投递参数':'创建并显示链接'}}</button></form></BaseDialog>
  <BaseDialog :open="shareEditOpen" title="编辑分享参数" @close="shareEditOpen=false"><form v-if="editingShare" class="stack" @submit.prevent="saveShare"><div class="status-callout"><Link2 :size="18"/><span><strong>{{editingShare.fileName||'单条内容分享'}}</strong><small>{{expiryLabel(editingShare)}} · {{downloadLabel(editingShare)}}</small></span></div><ShareParameterFields v-model:expires-in="editExpiresIn" v-model:max-downloads="editMaxDownloads" allow-unchanged :downloads="editingShare.downloads"/><button class="primary-button" :disabled="shareEditSaving||editExpiresIn===undefined&&editMaxDownloads===undefined">{{shareEditSaving?'保存中…':'保存分享参数'}}</button></form></BaseDialog>
  <LinkQrDialog :open="linkOpen" :title="linkTitle" :link="linkValue" :description="linkDescription" @close="linkOpen=false"/>
</section></template>
